/*
 MinPubSub
 a micro publish/subscribe messaging framework
 @see https://github.com/daniellmb/MinPubSub 
 @author Daniel Lamb <daniellmb.com>

 Released under the MIT License
 MelonJS Game Engine
 Copyright (C) 2012, Olivier BIOT
 http://www.melonjs.org

 melonJS is licensed under the MIT License.
 http://www.opensource.org/licenses/mit-license.php

 Tween JS
 https://github.com/sole/Tween.js
*/
var me=me||{};
(function(a){function b(){if(!f){if(!d.body)return setTimeout(b,13);d.removeEventListener?d.removeEventListener("DOMContentLoaded",b,!1):a.removeEventListener("load",b,!1);f=!0;for(var c=0;c<j.length;c++)j[c].call(a,[]);j.length=0}}function c(){return{xmlDoc:null,parseFromString:function(c){a.DOMParser?this.xmlDoc=(new DOMParser).parseFromString(c,"text/xml"):(this.xmlDoc=new ActiveXObject("Microsoft.XMLDOM"),this.xmlDoc.async="false",this.xmlDoc.loadXML(c));null==this.xmlDoc&&console.log("xml "+this.xmlDoc+
" not found!")},getFirstElementByTagName:function(a){return this.xmlDoc?this.xmlDoc.getElementsByTagName(a)[0]:null},getAllTagElements:function(){return this.xmlDoc?this.xmlDoc.getElementsByTagName("*"):null},getStringAttribute:function(a,c,d){return(a=a.getAttribute(c))?a.trim():d},getIntAttribute:function(a,c,d){return(a=this.getStringAttribute(a,c,d))?parseInt(a):d},getFloatAttribute:function(a,c,d){return(a=this.getStringAttribute(a,c,d))?parseFloat(a):d},getBooleanAttribute:function(a,c,d){return(a=
this.getStringAttribute(a,c,d))?"true"==a:d},free:function(){this.xmlDoc=null}}}var d=a.document;me={mod:"melonJS",version:"0.9.5",nocache:"",audio:null,video:null,timer:null,input:null,state:null,game:null,entityPool:null,levelDirector:null,XMLParser:null,loadingScreen:null,TMXTileMap:null};me.sys={ua:navigator.userAgent.toLowerCase(),sound:!1,localStorage:"object"==typeof a.localStorage,gyro:void 0!==a.DeviceMotionEvent,nativeBase64:"function"==typeof a.atob,touch:!1,fps:60,interpolation:!1,scale:null,
gravity:void 0,useNativeAnimFrame:!1,cacheImage:!1,dirtyRegion:!1,stopOnAudioError:!0,pauseOnBlur:!0,preRender:!1,checkVersion:function(a,c){for(var c=c||me.version,d=a.split("."),b=c.split("."),e=Math.min(d.length,b.length),f=0,g=0;g<e&&!(f=+d[g]-+b[g]);g++);return f?f:d.length-b.length}};var e=!1,g=!1,f=!1,j=[];a.onReady=function(c){g||(g=!0,"complete"===d.readyState?b():(d.addEventListener&&d.addEventListener("DOMContentLoaded",b,!1),a.addEventListener("load",b,!1)));f?c.call(a,[]):j.push(function(){return c.call(a,
[])});return this};a.onReady(function(){if(!e){var b=d.createElement("audio");me.utils.setNocache(d.location.href.match(/\?nocache/)||!1);b.canPlayType&&(me.audio.capabilities.mp3="no"!=b.canPlayType("audio/mpeg")&&""!=b.canPlayType("audio/mpeg"),me.audio.capabilities.ogg="no"!=b.canPlayType('audio/ogg; codecs="vorbis"')&&""!=b.canPlayType('audio/ogg; codecs="vorbis"'),me.audio.capabilities.wav="no"!=b.canPlayType('audio/wav; codecs="1"')&&""!=b.canPlayType('audio/wav; codecs="1"'),me.sys.sound=me.audio.capabilities.mp3||
me.audio.capabilities.ogg||me.audio.capabilities.wav);if(-1<me.sys.ua.search("iphone")||-1<me.sys.ua.search("ipod")||-1<me.sys.ua.search("ipad")||-1<me.sys.ua.search("android"))me.sys.sound=!1;me.sys.touch="createTouch"in d||"ontouchstart"in a;me.timer.init();me.XMLParser=new c;me.loadingScreen=new me.DefaultLoadingScreen;me.state.init();me.entityPool.init();me.levelDirector.reset();e=!0}});var l=!1,m=/xyz/.test(function(){})?/\bparent\b/:/.*/;Object.extend=function(a){function c(){!l&&this.init&&
this.init.apply(this,arguments)}var d=this.prototype;l=!0;var b=new this;l=!1;for(var e in a)b[e]="function"==typeof a[e]&&"function"==typeof d[e]&&m.test(a[e])?function(a,c){return function(){var b=this.parent;this.parent=d[a];var e=c.apply(this,arguments);this.parent=b;return e}}(e,a[e]):a[e];c.prototype=b;c.constructor=c;c.extend=Object.extend;return c};"function"!==typeof Object.create&&(Object.create=function(a){function c(){}c.prototype=a;return new c});Function.bind||(Function.prototype.bind=
function(){var a=this,c=Array.prototype.slice.call(arguments),d=c.shift();return function(){return a.apply(d,c.concat(Array.prototype.slice.call(arguments)))}});"undefined"===typeof Date.now&&(Date.now=function(){return(new Date).getTime()});"undefined"===typeof console&&(console={log:function(){},info:function(){},error:function(){alert(Array.prototype.slice.call(arguments).join(", "))}});Function.prototype.defer=function(){var a=this,c=Array.prototype.slice.call(arguments);return window.setTimeout(function(){return a.apply(a,
c)},0.01)};Object.defineProperty||(Object.defineProperty=function(a,c,d){if(a.__defineGetter__)d.get&&a.__defineGetter__(c,d.get),d.set&&a.__defineSetter__(c,d.set);else throw"melonJS: Object.defineProperty not supported";});String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+/,"").replace(/\s+$/,"")});String.prototype.isNumeric=function(){return null!=this&&!isNaN(this)&&""!=this.trim()};String.prototype.isBoolean=function(){return null!=this&&("true"==this.trim()||
"false"==this.trim())};String.prototype.contains=function(a){return-1<this.indexOf(a)};String.prototype.toHex=function(){for(var a="",c=0;c<this.length;)a+=this.charCodeAt(c++).toString(16);return a};Number.prototype.clamp=function(a,c){return this<a?a:this>c?c:+this};Number.prototype.random=function(a,c){return~~(Math.random()*(c-a+1))+a};Number.prototype.round=function(){var a=2>arguments.length?this:arguments[0],c=Math.pow(10,arguments[1]||arguments[0]||0);return Math.round(a*c)/c};Number.prototype.toHex=
function(){return"0123456789ABCDEF".charAt(this-this%16>>4)+"0123456789ABCDEF".charAt(this%16)};Number.prototype.sign=function(){return 0>this?-1:0<this?1:0};Number.prototype.degToRad=function(a){return(a||this)/180*Math.PI};Number.prototype.radToDeg=function(a){return(a||this)*(180/Math.PI)};Array.prototype.remove=function(a){a=Array.prototype.indexOf.call(this,a);-1!==a&&Array.prototype.splice.call(this,a,1);return this};Array.prototype.forEach||(Array.prototype.forEach=function(a,c){for(var d=
0,b=this.length;b--;d++)a.call(c||this,this[d],d,this)});Object.defineProperty(me,"initialized",{get:function(){return e}});var h={},n=[],r,k=[],t=0;h.isDirty=!1;h.reset=function(){n.length=0;k.length=0;r=me.game.viewport.getRect();h.makeAllDirty()};h.makeDirty=function(a,c,d){c&&(h.isDirty=!0,me.sys.dirtyRegion&&(d?n.push(d.union(a)):a.getRect&&n.push(a.getRect())));a.inViewport&&k.unshift(a)};h.makeAllDirty=function(){n.length=0;n.push(r);h.isDirty=!0};h.remove=function(a){var c=k.indexOf(a);-1!=
c&&(k.splice(c,1),a.inViewport=!1,h.makeDirty(a,!0))};h.getDrawCount=function(){return t};h.draw=function(a){var c=me.game.viewport.pos.x,d=me.game.viewport.pos.y;a.save();a.translate(-c,-d);for(var c=c-me.game.currentLevel.pos.x,d=d-me.game.currentLevel.pos.y,b=n.length,e;b--,e=n[b];){for(var g=k.length,f;g--,f=k[g];)if(!me.sys.dirtyRegion||!f.isSprite||f.overlaps(e))!0===f.floating&&(a.save(),a.translate(c,d)),f.draw(a,e),!0===f.floating&&a.restore(),t++;me.debug.renderDirty&&e.draw(a,"white")}a.restore()};
h.flush=function(){me.sys.dirtyRegion&&(n.length=0);k.length=0;h.isDirty=!1;t=0};var v=me,i={},w=null,s=[],A=!1,x=null,u=null,B=function(a,c){return c.z-a.z};i.viewport=null;i.HUD=null;i.collisionMap=null;i.currentLevel=null;i.NO_OBJECT=0;i.ENEMY_OBJECT=1;i.COLLECTABLE_OBJECT=2;i.ACTION_OBJECT=3;i.onLevelLoaded=null;i.init=function(a,c){A||(a=a||me.video.getWidth(),c=c||me.video.getHeight(),i.viewport=new me.Viewport(0,0,a,c),w=me.video.getScreenFrameBuffer(),me.event.publish(me.event.GAME_INIT),
A=!0)};i.reset=function(){A||i.init();i.removeAll();i.viewport&&i.viewport.reset();h.reset();w.setTransform(1,0,0,1,0,0);i.currentLevel={pos:{x:0,y:0}}};i.loadTMXLevel=function(a){i.currentLevel=a;i.collisionMap=i.currentLevel.getLayerByName("collision");(!i.collisionMap||!i.collisionMap.isCollisionMap)&&console.error("WARNING : no collision map detected");for(var c=i.currentLevel.getLayers(),d=c.length;d--;)c[d].visible&&i.add(c[d]);i.viewport.setBounds(Math.max(i.currentLevel.realwidth,i.viewport.width),
Math.max(i.currentLevel.realheight,i.viewport.height));c=i.currentLevel.getObjectGroups();for(d=0;d<c.length;d++)if(c[d].visible)for(var b=0;b<c[d].objects.length;b++)i.addEntity(c[d].objects[b],c[d].z);i.currentLevel.pos.x!=i.currentLevel.pos.y&&w.translate(i.currentLevel.pos.x,i.currentLevel.pos.y);i.sort();i.onLevelLoaded&&i.onLevelLoaded.call(i.onLevelLoaded,a.name);me.event.publish(me.event.LEVEL_LOADED,[a.name])};i.add=function(a,c){a.z=c?c:a.z;s.push(a)};i.addEntity=function(a,c){var d=me.entityPool.newInstanceOf(a);
d&&i.add(d,c)};i.getEntityByName=function(a){for(var c=[],a=a.toLowerCase(),d=s.length,b;d--,b=s[d];)b.name==a&&c.push(b);return c};i.getObjectCount=function(){return s.length};i.getDrawCount=function(){return h.getDrawCount()};i.getEntityByGUID=function(a){for(var c=s.length,d;c--,d=s[c];)if(d.isEntity&&d.GUID==a)return d;return null};i.addHUD=function(a,c,d,b,e){null==i.HUD&&(i.HUD=new me.HUD_Object(a,c,d,b,e),i.add(i.HUD))};i.disableHUD=function(){null!=i.HUD&&(i.remove(i.HUD),i.HUD=null)};i.update=
function(){for(var a=null,c=s.length,d;c--,d=s[c];){var a=me.sys.dirtyRegion&&d.isSprite?d.getRect():null,b=d.update();d.inViewport=d.visible?!d.isSprite||d.floating?!0:i.viewport.isVisible(d):!1;h.makeDirty(d,b,b?a:null)}i.viewport.update(h.isDirty)&&h.makeAllDirty()};i.remove=function(a,c){a.destroy&&a.destroy();h.remove(a);!0===c?s.remove(a):(a.visible=!1,x=function(a){s.remove(a);x=null}.defer(a))};i.removeAll=function(){x&&(clearTimeout(x),x=null);u&&(clearTimeout(u),u=null);for(var a=s.length;a--;)s[a].isPersistent||
i.remove(s[a],!0);h.flush()};i.sort=function(a){null===u&&("function"!==typeof a&&(a=B),u=function(a){s.sort(a);u=null;me.game.repaint()}.defer(a))};i.collide=function(a){for(var c=null,d=s.length,b;d--,b=s[d];)if(b.inViewport&&(b.visible&&b.collidable&&b.isEntity&&b!=a)&&(c=b.collisionBox.collideVsAABB.call(b,a),0!=c.x||0!=c.y))return b.onCollision.call(b,c,a),c.type=b.type,c.obj=b,c;return null};i.repaint=function(){h.makeAllDirty()};i.draw=function(){h.isDirty&&(h.draw(w),i.viewport.draw(w));h.flush()};
v.game=i;me.ScreenObject=Object.extend({inViewport:!1,visible:!1,addAsObject:!1,isPersistent:!1,z:999,rect:null,init:function(a,c){this.isPersistent=(this.addAsObject=this.visible=!0===a||!1)&&!0===c||!1;this.rect=new me.Rect(new me.Vector2d(0,0),0,0)},reset:function(){me.game.reset();this.onResetEvent.apply(this,arguments);this.addAsObject&&(this.visible=!0,this.rect=me.game.viewport.getRect(),me.game.add(this,this.z));me.game.sort()},getRect:function(){return this.rect},destroy:function(){this.onDestroyEvent.apply(this,
arguments)},update:function(){return!1},onUpdateFrame:function(){me.timer.update();me.game.update();me.game.draw();me.video.blitSurface()},draw:function(){},onResetEvent:function(){},onDestroyEvent:function(){}});for(var v=me,M=function(){if(-1==D&&-1==C){me.timer.reset();if(me.sys.useNativeAnimFrame){C=window.requestAnimationFrame(L);if(-1!=C)return;me.sys.useNativeAnimFrame=!1}D=setInterval(H,~~(1E3/me.sys.fps))}},L=function(){H();C=window.requestAnimationFrame(L)},N=function(){-1!=D&&(clearInterval(D),
D=-1);-1!=C&&(window.cancelAnimationFrame(C),C=-1)},O=function(a){N();y[z]&&(y[z].screen.visible&&me.game.remove.call(me.game,y[z].screen,!0),y[z].screen.destroy());y[a]&&(z=a,y[z].screen.reset.apply(y[z].screen,I),H=y[z].screen.onUpdateFrame.bind(y[z].screen),M(),J&&J(),me.game.repaint())},F=["ms","moz","webkit","o"],E=0;E<F.length&&!window.requestAnimationFrame;++E)window.requestAnimationFrame=window[F[E]+"RequestAnimationFrame"],window.cancelAnimationFrame=window[F[E]+"CancelAnimationFrame"]||
window[F[E]+"CancelRequestAnimationFrame"];window.requestAnimationFrame||(window.requestAnimationFrame=function(){return-1});window.cancelAnimationFrame||(window.cancelAnimationFrame=function(){return-1});var q={},z=-1,D=-1,C=-1,y={},K="",G=0,J=null,I=null,H=null;q.LOADING=0;q.MENU=1;q.READY=2;q.PLAY=3;q.GAMEOVER=4;q.GAME_END=5;q.SCORE=6;q.CREDITS=7;q.SETTINGS=8;q.USER=100;q.onPause=null;q.onResume=null;q.init=function(){q.set(q.LOADING,me.loadingScreen);a.addEventListener("blur",function(){me.sys.pauseOnBlur&&
z!=q.LOADING&&q.pause(!0);if(q.onPause)q.onPause();me.event.publish(me.event.STATE_PAUSE)},!1);a.addEventListener("focus",function(){me.sys.pauseOnBlur&&z!=q.LOADING&&(q.resume(!0),me.game.repaint());if(q.onResume)q.onResume();me.event.publish(me.event.STATE_RESUME)},!1)};q.pause=function(a){N();a&&me.audio.pauseTrack()};q.resume=function(a){M();a&&me.audio.resumeTrack()};q.isRunning=function(){return-1!=D||-1!=C};q.set=function(a,c){y[a]={};y[a].screen=c;y[a].transition=!0};q.current=function(){return y[z].screen};
q.transition=function(a,c,d){"fade"==a&&(K=c,G=d)};q.setTransition=function(a,c){y[a].transition=c};q.change=function(a){I=null;1<arguments.length&&(I=Array.prototype.slice.call(arguments,1));G&&y[a].transition?(J=function(){me.game.viewport.fadeOut(K,G)},me.game.viewport.fadeIn(K,G,function(){O.defer(a)})):O.defer(a)};q.isCurrent=function(a){return z==a};v.state=q})(window);
(function(){me.DefaultLoadingScreen=me.ScreenObject.extend({init:function(){this.parent(!0);this.logo1=new me.Font("century gothic",32,"white","middle");this.logo2=new me.Font("century gothic",32,"#89b002","middle");this.logo2.bold();this.invalidate=!1;this.handle=null;this.loadPercent=0},onResetEvent:function(){this.handle=me.event.subscribe(me.event.LOADER_PROGRESS,this.onProgressUpdate.bind(this))},onDestroyEvent:function(){this.logo1=this.logo2=null;this.handle&&(me.event.unsubscribe(this.handle),
this.handle=null)},onProgressUpdate:function(a){this.loadPercent=a;this.invalidate=!0},update:function(){return!0===this.invalidate?(this.invalidate=!1,!0):!1},draw:function(a){var c=this.logo1.measureText(a,"melon").width,d=(me.video.getWidth()-c-this.logo2.measureText(a,"JS").width)/2,b=me.video.getHeight()/2;me.video.clearSurface(a,"black");this.logo1.draw(a,"melon",d,b);this.logo2.draw(a,"JS",d+c,b);b+=this.logo1.measureText(a,"melon").height/2;c=Math.floor(this.loadPercent*me.video.getWidth());
a.strokeStyle="silver";a.strokeRect(0,b,me.video.getWidth(),6);a.fillStyle="#89b002";a.fillRect(2,b+2,c-4,2)}});var a=me,b=function(){if(l==j-h){for(var a in g)if(g[a].isTMX&&me.levelDirector.addTMXLevel(a))d.onResourceLoaded();d.onload?(clearTimeout(m),setTimeout(function(){d.onload();me.event.publish(me.event.LOADER_COMPLETE)},300),h=0):console.error("no load callback defined")}else m=setTimeout(b,100)},c=function(a,c,d){var b=new XMLHttpRequest;b.overrideMimeType&&b.overrideMimeType("text/xml");
b.onerror=d;b.open("GET",a.src+me.nocache,!1);b.send();g[a.name]={xml:b.responseText,isTMX:"tmx"===a.type};c()},d={},e={},g={},f={},j=0,l=0,m=0,h=0;d.onload=void 0;d.onProgress=void 0;d.onResourceLoaded=function(){l++;var a=d.getLoadProgress();if(d.onProgress)d.onProgress(a);me.event.publish(me.event.LOADER_PROGRESS,[a])};d.onLoadingError=function(a){throw"melonJS: Failed loading resource "+a.src;};d.preload=function(a){for(var c=0;c<a.length;c++)j+=d.load(a[c],d.onResourceLoaded.bind(d),d.onLoadingError.bind(d,
a[c]));b()};d.load=function(a,d,b){a.name=a.name.toLowerCase();switch(a.type){case "binary":var g=new XMLHttpRequest;g.open("GET",a.src+me.nocache,!1);g.responseType="arraybuffer";xmlhttp.onerror=b;g.onload=function(){var c=g.response;if(c){var c=new Uint8Array(c),b=[];f[a.name]=new dataType;for(var e=0;e<c.byteLength;e++)b[e]=String.fromCharCode(c[e]);f[a.name].data=b.join("");d()}};g.send();return 1;case "image":return e[a.name]=new Image,e[a.name].onload=d,e[a.name].onerror=b,e[a.name].src=a.src+
me.nocache,1;case "tmx":return c.call(this,a,d,b),h+=1,2;case "tsx":return c.call(this,a,d,b),1;case "audio":me.audio.setLoadCallback(d);if(me.audio.isAudioEnable())return me.audio.load(a),1;break;default:throw"melonJS: me.loader.load : unknown or invalid resource type : "+a.type;}return 0};d.unload=function(a){a.name=a.name.toLowerCase();switch(a.type){case "binary":if(!(a.name in f))return!1;delete f[a.name];return!0;case "image":if(!(a.name in e))return!1;delete e[a.name];return!0;case "tmx":case "tsx":if(!(a.name in
g))return!1;delete g[a.name];return!0;case "audio":return me.audio.unload(a.name);default:throw"melonJS: me.loader.unload : unknown or invalid resource type : "+a.type;}};d.unloadAll=function(){for(var a in f)d.unload(a);for(a in e)d.unload(a);for(a in g)d.unload(a);me.audio.unloadAll()};d.getXML=function(a){a=a.toLowerCase();return a in g?g[a].xml:null};d.getBinary=function(a){a=a.toLowerCase();return a in f?f[a]:null};d.getImage=function(a){a=a.toLowerCase();if(a in e){if(!0===me.sys.cacheImage){var c=
me.video.createCanvasSurface(e[a].width,e[a].height);c.drawImage(e[a],0,0);return c.canvas}return e[a]}return null};d.getLoadProgress=function(){return l/j};a.loader=d})(window);
(function(){me.Vector2d=Object.extend({x:0,y:0,init:function(a,b){this.x=a||0;this.y=b||0},set:function(a,b){this.x=a;this.y=b},setZero:function(){this.set(0,0)},setV:function(a){this.x=a.x;this.y=a.y},add:function(a){this.x+=a.x;this.y+=a.y},sub:function(a){this.x-=a.x;this.y-=a.y},scale:function(a){this.x*=a.x;this.y*=a.y},div:function(a){this.x/=a;this.y/=a},abs:function(){0>this.x&&(this.x=-this.x);0>this.y&&(this.y=-this.y)},clamp:function(a,b){return new me.Vector2d(this.x.clamp(a,b),this.y.clamp(a,
b))},clampSelf:function(a,b){this.x=this.x.clamp(a,b);this.y=this.y.clamp(a,b);return this},minV:function(a){this.x=this.x<a.x?this.x:a.x;this.y=this.y<a.y?this.y:a.y},maxV:function(a){this.x=this.x>a.x?this.x:a.x;this.y=this.y>a.y?this.y:a.y},floor:function(){return new me.Vector2d(~~this.x,~~this.y)},floorSelf:function(){this.x=~~this.x;this.y=~~this.y;return this},ceil:function(){return new me.Vector2d(Math.ceil(this.x),Math.ceil(this.y))},ceilSelf:function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);
return this},negate:function(){return new me.Vector2d(-this.x,-this.y)},negateSelf:function(){this.x=-this.x;this.y=-this.y;return this},copy:function(a){this.x=a.x;this.y=a.y},equals:function(a){return this.x===a.x&&this.y===a.y},length:function(){return Math.sqrt(this.x*this.x+this.y*this.y)},normalize:function(){var a=this.length();if(a<Number.MIN_VALUE)return 0;var b=1/a;this.x*=b;this.y*=b;return a},dotProduct:function(a){return this.x*a.x+this.y*a.y},distance:function(a){return Math.sqrt((this.x-
a.x)*(this.x-a.x)+(this.y-a.y)*(this.y-a.y))},clone:function(){return new me.Vector2d(this.x,this.y)},toString:function(){return"x:"+this.x+"y:"+this.y}});me.Rect=Object.extend({pos:null,colPos:null,width:0,height:0,hWidth:0,hHeight:0,init:function(a,b,c){this.pos=a;this.colPos=new me.Vector2d;this.width=b;this.height=c;this.hWidth=~~(b/2);this.hHeight=~~(c/2);Object.defineProperty(this,"left",{get:function(){return this.pos.x},configurable:!0});Object.defineProperty(this,"right",{get:function(){return this.pos.x+
this.width},configurable:!0});Object.defineProperty(this,"top",{get:function(){return this.pos.y},configurable:!0});Object.defineProperty(this,"bottom",{get:function(){return this.pos.y+this.height},configurable:!0})},set:function(a,b,c){this.pos=a;this.width=b;this.height=c;this.hWidth=~~(b/2);this.hHeight=~~(c/2)},getRect:function(){return new me.Rect(this.pos.clone(),this.width,this.height)},union:function(a){var b=Math.min(this.pos.x,a.pos.x),c=Math.min(this.pos.y,a.pos.y);this.width=Math.ceil(Math.max(this.pos.x+
this.width,a.pos.x+a.width)-b);this.height=Math.ceil(Math.max(this.pos.y+this.height,a.pos.y+a.height)-c);this.pos.x=~~b;this.pos.y=~~c;return this},adjustSize:function(a,b,c,d){-1!=a&&(this.colPos.x=a,this.width=b,this.hWidth=~~(this.width/2),this.left!==this.pos.x+this.colPos.x&&Object.defineProperty(this,"left",{get:function(){return this.pos.x+this.colPos.x},configurable:!0}),this.right!==this.pos.x+this.colPos.x+this.width&&Object.defineProperty(this,"right",{get:function(){return this.pos.x+
this.colPos.x+this.width},configurable:!0}));-1!=c&&(this.colPos.y=c,this.height=d,this.hHeight=~~(this.height/2),this.top!==this.pos.y+this.colPos.y&&Object.defineProperty(this,"top",{get:function(){return this.pos.y+this.colPos.y},configurable:!0}),this.bottom!==this.pos.y+this.colPos.y+this.height&&Object.defineProperty(this,"bottom",{get:function(){return this.pos.y+this.colPos.y+this.height},configurable:!0}))},flipX:function(a){this.colPos.x=a-this.width-this.colPos.x;this.hWidth=~~(this.width/
2)},flipY:function(a){this.colPos.y=a-this.height-this.colPos.y;this.hHeight=~~(this.height/2)},overlaps:function(a){return this.left<a.right&&a.left<this.right&&this.top<a.bottom&&a.top<this.bottom},within:function(a){return a.left<=this.left&&a.right>=this.right&&a.top<=this.top&&a.bottom>=this.bottom},contains:function(a){return a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom},containsPoint:function(a){return a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom},
collideVsAABB:function(a){var b=new me.Vector2d(0,0);if(this.overlaps(a)){var c=this.left+this.hWidth-a.left-a.hWidth,d=this.top+this.hHeight-a.top-a.hHeight;b.x=a.hWidth+this.hWidth-(0>c?-c:c);b.y=a.hHeight+this.hHeight-(0>d?-d:d);b.x<b.y?(b.y=0,b.x=0>c?-b.x:b.x):(b.x=0,b.y=0>d?-b.y:b.y)}return b},draw:function(a,b){a.strokeStyle=b||"red";a.strokeRect(this.left,this.top,this.width,this.height)}})})(window);
(function(){me.debug={displayFPS:!1,renderHitBox:!1,renderCollisionMap:!1,renderDirty:!1,renderVelocity:!1,showPanel:function(){var a=me.game.getEntityByName("me.debugPanel")[0];a?a.show():(a=new me.debug.Panel,me.game.add(a),me.game.sort());me.debug.displayFPS=!0}};me.debug.Panel=me.Rect.extend({GUID:null,area:{},z:Infinity,visible:!1,init:function(){this.parent(new me.Vector2d(0,0),me.video.getWidth(),35);this.GUID=me.utils.createGUID();this.name="me.debugPanel";this.floating=this.isPersistent=
!0;this.font=new me.Font("courier",10,"white");this.area.renderHitBox=new me.Rect(new me.Vector2d(160,5),15,15);this.area.renderVelocity=new me.Rect(new me.Vector2d(165,25),15,15);this.area.renderDirty=new me.Rect(new me.Vector2d(270,5),15,15);this.area.renderCollisionMap=new me.Rect(new me.Vector2d(270,25),15,15);this.help_str="(s)how/(h)ide";this.help_str_len=this.font.measureText(me.video.getScreenFrameBuffer(),this.help_str).width;this.fps_str_len=this.font.measureText(me.video.getScreenFrameBuffer(),
"00/00 fps").width;me.input.bindKey(me.input.KEY.S,"show");me.input.bindKey(me.input.KEY.H,"hide");this.samples=[];this.show()},show:function(){this.visible||(this.pos.y=0,me.input.registerMouseEvent("mousedown",this,this.onClick.bind(this)),this.visible=!0,me.game.repaint())},hide:function(){this.visible&&(this.pos.y=-this.height,me.input.releaseMouseEvent("mousedown",this),this.visible=!1,me.game.repaint())},update:function(){me.input.isKeyPressed("show")?this.show():me.input.isKeyPressed("hide")&&
this.hide();return!0},onClick:function(){this.area.renderHitBox.containsPoint(me.input.mouse.pos)?me.debug.renderHitBox=!me.debug.renderHitBox:this.area.renderDirty.containsPoint(me.input.mouse.pos)?me.debug.renderDirty=!me.debug.renderDirty:this.area.renderCollisionMap.containsPoint(me.input.mouse.pos)?me.debug.renderCollisionMap=!me.debug.renderCollisionMap:this.area.renderVelocity.containsPoint(me.input.mouse.pos)&&(me.debug.renderVelocity=!me.debug.renderVelocity);me.game.repaint()},drawMemoryGraph:function(a,
b,c){if(window.performance&&window.performance.memory){var d=Number.prototype.round(window.performance.memory.usedJSHeapSize/1048576,2),e=Number.prototype.round(window.performance.memory.totalJSHeapSize/1048576,2),g=c-b;this.samples.shift();this.samples[g]=25*(d/e);for(var f=g;f--;){var j=c-(g-f);a.beginPath();a.strokeStyle="lightgreen";a.moveTo(j,30);a.lineTo(j,30-(this.samples[f]||0));a.stroke()}this.font.draw(a,d+"/"+e+" MB",b,5)}else this.font.draw(a,"??/?? MB",b,5)},draw:function(a){a.save();
a.globalAlpha=0.5;a.fillStyle="black";a.fillRect(this.left,this.top,this.width,this.height);a.globalAlpha=1;this.font.draw(a,"#objects : "+me.game.getObjectCount(),5,5);this.font.draw(a,"#draws   : "+me.game.getDrawCount(),5,20);this.font.draw(a,"?hitbox   ["+(me.debug.renderHitBox?"x":" ")+"]",100,5);this.font.draw(a,"?velocity ["+(me.debug.renderVelocity?"x":" ")+"]",100,20);this.font.draw(a,"?dirtyRect  ["+(me.debug.renderDirty?"x":" ")+"]",200,5);this.font.draw(a,"?col. layer ["+(me.debug.renderCollisionMap?
"x":" ")+"]",200,20);this.drawMemoryGraph(a,300,this.width-this.help_str_len-15);this.font.draw(a,this.help_str,this.width-this.help_str_len-5,20);this.font.draw(a,""+me.timer.fps+"/"+me.sys.fps+" fps",this.width-this.fps_str_len-5,5);a.restore()},onDestroyEvent:function(){this.hide();me.input.unbindKey(me.input.KEY.S);me.input.unbindKey(me.input.KEY.H)}})})(window);
(function(){var a=Math.min,b=Math.max;me.Viewport=me.Rect.extend({AXIS:{NONE:0,HORIZONTAL:1,VERTICAL:2,BOTH:3},limits:null,target:null,follow_axis:0,_shake:null,_fadeIn:null,_fadeOut:null,_deadwidth:0,_deadheight:0,_limitwidth:0,_limitheight:0,init:function(a,d,b,g,f,j){this.parent(new me.Vector2d(a,d),b-a,g-d);this.limits=new me.Vector2d(f||this.width,j||this.height);this.target=null;this.follow_axis=this.AXIS.NONE;this._shake={intensity:0,duration:0,axis:this.AXIS.BOTH,onComplete:null};this._fadeOut=
{color:0,alpha:0,duration:0,tween:null};this._fadeIn={color:0,alpha:1,duration:0,tween:null};this.setDeadzone(this.width/6,this.height/6)},_followH:function(c){return c.x-this.pos.x>this._deadwidth?(this.pos.x=~~a(c.x-this._deadwidth,this._limitwidth),!0):c.x-this.pos.x<this.deadzone.x?(this.pos.x=~~b(c.x-this.deadzone.x,0),!0):!1},_followV:function(c){return c.y-this.pos.y>this._deadheight?(this.pos.y=~~a(c.y-this._deadheight,this._limitheight),!0):c.y-this.pos.y<this.deadzone.y?(this.pos.y=~~b(c.y-
this.deadzone.y,0),!0):!1},reset:function(a,d){this.pos.x=a||0;this.pos.y=d||0;this.follow_axis=this.target=null},setDeadzone:function(a,d){this.deadzone=new me.Vector2d(~~((this.width-a)/2),~~((this.height-d)/2-0.25*d));this._deadwidth=this.width-this.deadzone.x;this._deadheight=this.height-this.deadzone.y;this.update(!0)},setBounds:function(a,d){this.limits.set(a,d);this._limitwidth=this.limits.x-this.width;this._limitheight=this.limits.y-this.height},follow:function(a,d){if(a instanceof me.ObjectEntity)this.target=
a.pos;else if(a instanceof me.Vector2d)this.target=a;else throw"melonJS: invalid target for viewport.follow";this.follow_axis=d||this.AXIS.BOTH;this.update(!0)},move:function(a,d){var b=~~(this.pos.y+d);this.pos.x=(~~(this.pos.x+a)).clamp(0,this._limitwidth);this.pos.y=b.clamp(0,this._limitheight)},update:function(a){if(this.target&&a)switch(this.follow_axis){case this.AXIS.HORIZONTAL:a=this._followH(this.target);break;case this.AXIS.VERTICAL:a=this._followV(this.target);break;case this.AXIS.BOTH:a=
this._followH(this.target),a=this._followV(this.target)||a}if(0<this._shake.duration)if(this._shake.duration-=me.timer.tick,0>this._shake.duration){if(this._shake.onComplete)this._shake.onComplete()}else{if(this._shake.axis==this.AXIS.BOTH||this._shake.axis==this.AXIS.HORIZONTAL)a=Math.random()*this._shake.intensity,this.pos.x=this.pos.x+this.width+a<this.limits.x?this.pos.x+~~a:this.pos.x-~~a;if(this._shake.axis==this.AXIS.BOTH||this._shake.axis==this.AXIS.VERTICAL)a=Math.random()*this._shake.intensity,
this.pos.y=this.pos.y+this.height+a<this.limits.y?this.pos.y+~~a:this.pos.y-~~a;a=!0}if(null!=this._fadeIn.tween||null!=this._fadeOut.tween)a=!0;return a},shake:function(a,d,b,g){b=b||this.AXIS.BOTH;b==this.AXIS.BOTH&&(this.width==this.limits.x?b=this.AXIS.VERTICAL:this.height==this.limits.y&&(b=this.AXIS.HORIZONTAL));!(b==this.AXIS.HORIZONTAL&&this.width==this.limits.x)&&!(b==this.AXIS.VERTICAL&&this.height==this.limits.y)&&(this._shake.intensity=a,this._shake.duration=d,this._shake.axis=b,this._shake.onComplete=
g||null)},fadeOut:function(a,d,b){this._fadeOut.color=a;this._fadeOut.duration=d||1E3;this._fadeOut.alpha=1;this._fadeOut.tween=(new me.Tween(this._fadeOut)).to({alpha:0},this._fadeOut.duration).onComplete(b||null);this._fadeOut.tween.start()},fadeIn:function(a,d,b){this._fadeIn.color=a;this._fadeIn.duration=d||1E3;this._fadeIn.alpha=0;this._fadeIn.tween=(new me.Tween(this._fadeIn)).to({alpha:1},this._fadeIn.duration).onComplete(b||null);this._fadeIn.tween.start()},getWidth:function(){return this.width},
getHeight:function(){return this.height},focusOn:function(a){this.pos.x=a.x-0.5*this.width;this.pos.y=a.y-0.5*this.height},isVisible:function(a){return a.overlaps(this)},draw:function(a){this._fadeIn.tween&&(a.globalAlpha=this._fadeIn.alpha,me.video.clearSurface(a,me.utils.HexToRGB(this._fadeIn.color)),a.globalAlpha=1,1==this._fadeIn.alpha&&(this._fadeIn.tween=null));this._fadeOut.tween&&(a.globalAlpha=this._fadeOut.alpha,me.video.clearSurface(a,me.utils.HexToRGB(this._fadeOut.color)),a.globalAlpha=
1,0==this._fadeOut.alpha&&(this._fadeOut.tween=null))}})})(window);
(function(){me.SpriteObject=me.Rect.extend({scale:null,scaleFlag:!1,lastflipX:!1,lastflipY:!1,z:0,offset:null,visible:!0,inViewport:!1,angle:0,anchorPoint:null,alpha:1,floating:!1,image:null,flickering:!1,flickerTimer:-1,flickercb:null,flickerState:!1,vp:null,init:function(a,b,c,d,e){this.isSprite=!0;this.parent(new me.Vector2d(a,b),d||c.width,e||c.height);this.image=c;this.scale=new me.Vector2d(1,1);this.offset=new me.Vector2d(0,0);this.anchorPoint=new me.Vector2d(0.5,0.5);this.alpha=1;this.spritecount=
new me.Vector2d(~~(this.image.width/this.width),~~(this.image.height/this.height))},setTransparency:function(a){a="#"==a.charAt(0)?a.substring(1,7):a;this.image=me.video.applyRGBFilter(this.image,"transparent",a.toUpperCase()).canvas},isFlickering:function(){return this.flickering},flicker:function(a,b){this.flickerTimer=a;0>this.flickerTimer?(this.flickering=!1,this.flickercb=null):this.flickering||(this.flickercb=b,this.flickering=!0)},flipX:function(a){a!=this.lastflipX&&(this.lastflipX=a,this.scale.x=
-this.scale.x,this.scaleFlag=1!=this.scale.x||1!=this.scale.y)},flipY:function(a){a!=this.lastflipY&&(this.lastflipY=a,this.scale.y=-this.scale.y,this.scaleFlag=1!=this.scale.x||1!=this.scale.y)},resize:function(a){0<a&&(this.scale.x=0>this.scale.x?-a:a,this.scale.y=0>this.scale.y?-a:a,this.scaleFlag=1!=this.scale.x||1!=this.scale.y)},getOpacity:function(){return this.alpha},setOpacity:function(a){a&&(this.alpha=a.clamp(0,1))},update:function(){return this.flickering?(this.flickerTimer-=me.timer.tick,
0>this.flickerTimer&&(this.flickercb&&this.flickercb(),this.flicker(-1)),!0):!1},draw:function(a){if(this.flickering&&(this.flickerState=!this.flickerState,!this.flickerState))return;a.save();a.globalAlpha=this.alpha;var b=~~this.pos.x,c=~~this.pos.y;if(this.scaleFlag||0!==this.angle){var d=this.width*this.anchorPoint.x,e=this.height*this.anchorPoint.y;a.translate(b+d,c+e);this.scaleFlag&&a.scale(this.scale.x,this.scale.y);0!==this.angle&&a.rotate(this.angle);b=-d;c=-e}a.drawImage(this.image,this.offset.x,
this.offset.y,this.width,this.height,b,c,this.width,this.height);a.restore();me.debug.renderHitBox&&this.parent(a,"blue")},destroy:function(){this.onDestroyEvent.apply(this,arguments)},onDestroyEvent:function(){}});me.AnimationSheet=me.SpriteObject.extend({fpscount:0,animationpause:!1,animationspeed:0,init:function(a,b,c,d,e){this.anim=[];this.current=this.resetAnim=null;this.parent(a,b,c,d,e);1==this.spritecount.x*this.spritecount.y&&(this.setAnimationFrame=function(){});this.animationspeed=me.sys.fps/
10;this.addAnimation("default",null);this.setCurrentAnimation("default")},addAnimation:function(a,b){this.anim[a]={name:a,frame:[],idx:0,length:0};if(null==b)for(var b=[],c=0,d=this.spritecount.x*this.spritecount.y;c<d;c++)b[c]=c;c=0;for(d=b.length;c<d;c++)this.anim[a].frame[c]=new me.Vector2d(this.width*(b[c]%this.spritecount.x),this.height*~~(b[c]/this.spritecount.x));this.anim[a].length=this.anim[a].frame.length},setCurrentAnimation:function(a,b){this.current=this.anim[a];this.resetAnim=b||null;
this.setAnimationFrame(this.current.idx)},isCurrentAnimation:function(a){return this.current.name==a},setAnimationFrame:function(a){this.current.idx=(a||0)%this.current.length;this.offset=this.current.frame[this.current.idx]},update:function(){this.parent();return this.visible&&!this.animationpause&&this.fpscount++>this.animationspeed?(this.setAnimationFrame(++this.current.idx),this.fpscount=0,0==this.current.idx&&this.resetAnim&&("string"==typeof this.resetAnim?this.setCurrentAnimation(this.resetAnim):
"function"==typeof this.resetAnim&&this.resetAnim()),!0):!1}})})(window);
(function(){me.ObjectSettings={name:null,image:null,transparent_color:null,spritewidth:null,spriteheight:null,type:0,collidable:!1};var a=me,b={},c={};b.init=function(){b.add("me.LevelEntity",me.LevelEntity);b.add("me.ObjectEntity",me.ObjectEntity);b.add("me.CollectableEntity",me.CollectableEntity);b.add("me.InvisibleEntity",me.InvisibleEntity)};b.add=function(a,b){c[a.toLowerCase()]=b};b.newInstanceOf=function(a){var b=a.name?a.name.toLowerCase():void 0;if(b&&c[b])return new c[b](a.x,a.y,a);if(a.image)return new me.SpriteObject(a.x,
a.y,a.image);b&&console.error("Cannot instantiate entity of type '"+b+"': Class not found!");return null};a.entityPool=b;me.ObjectEntity=me.AnimationSheet.extend({GUID:null,type:0,collidable:!1,collisionBox:null,init:function(a,c,b){this.parent(a,c,"string"==typeof b.image?me.loader.getImage(b.image):b.image,b.spritewidth,b.spriteheight);b.transparent_color&&this.setTransparency(b.transparent_color);this.GUID=me.utils.createGUID();this.name=b.name?b.name.toLowerCase():"";this.vel=new me.Vector2d;
this.accel=new me.Vector2d;this.friction=new me.Vector2d;this.maxVel=new me.Vector2d(1E3,1E3);this.gravity=void 0!=me.sys.gravity?me.sys.gravity:0.98;this.alive=this.isEntity=!0;this.falling=!1;this.jumping=!0;this.slopeY=0;this.onladder=this.onslope=!1;this.collidable=b.collidable||!1;this.type=b.type||0;this.collisionMap=me.game.collisionMap;this.collisionBox=new me.Rect(this.pos,this.width,this.height);this.canBreakTile=!1;this.onTileBreak=null},updateColRect:function(a,c,b,f){this.collisionBox.adjustSize(a,
c,b,f)},onCollision:function(){this.collidable&&this.type==me.game.COLLECTABLE_OBJECT&&me.game.remove(this)},setVelocity:function(a,c){this.accel.x=0!=a?a:this.accel.x;this.accel.y=0!=c?c:this.accel.y;this.setMaxVelocity(a,c)},setMaxVelocity:function(a,c){this.maxVel.x=a;this.maxVel.y=c},setFriction:function(a,c){this.friction.x=a||0;this.friction.y=c||0},flipX:function(a){a!=this.lastflipX&&(this.parent(a),this.collisionBox.flipX(this.width))},flipY:function(a){a!=this.lastflipY&&(this.parent(a),
this.collisionBox.flipY(this.height))},doWalk:function(a){this.flipX(a);this.vel.x+=a?-this.accel.x*me.timer.tick:this.accel.x*me.timer.tick},doClimb:function(a){return this.onladder?(this.vel.y=a?-this.accel.x*me.timer.tick:this.accel.x*me.timer.tick,!0):!1},doJump:function(){return!this.jumping&&!this.falling?(this.vel.y=-this.maxVel.y*me.timer.tick,this.jumping=!0):!1},forceJump:function(){this.jumping=this.falling=!1;this.doJump()},distanceTo:function(a){var c=this.pos.x+this.hWidth-(a.pos.x+
a.hWidth),a=this.pos.y+this.hHeight-(a.pos.y+a.hHeight);return Math.sqrt(c*c+a*a)},checkSlope:function(a,c){this.pos.y=a.pos.y-this.height;this.slopeY=c?a.height-(this.collisionBox.right+this.vel.x-a.pos.x):this.collisionBox.left+this.vel.x-a.pos.x;this.vel.y=0;this.pos.y+=this.slopeY.clamp(0,a.height)},computeVelocity:function(a){this.gravity&&(a.y+=!this.onladder?this.gravity*me.timer.tick:0,this.jumping=(this.falling=0<a.y)?!1:this.jumping);this.friction.x&&(a.x=me.utils.applyFriction(a.x,this.friction.x));
this.friction.y&&(a.y=me.utils.applyFriction(a.y,this.friction.y));0!=a.y&&(a.y=a.y.clamp(-this.maxVel.y,this.maxVel.y));0!=a.x&&(a.x=a.x.clamp(-this.maxVel.x,this.maxVel.x))},updateMovement:function(){this.computeVelocity(this.vel);var a=this.collisionMap.checkCollision(this.collisionBox,this.vel);this.onslope=a.yprop.isSlope||a.xprop.isSlope;this.onladder=!1;if(a.y)if(this.onladder=a.yprop.isLadder,0<a.y)if(a.yprop.isSolid||a.yprop.isPlatform&&this.collisionBox.bottom-1<=a.ytile.pos.y)this.pos.y=
~~this.pos.y,this.vel.y=this.falling?a.ytile.pos.y-this.collisionBox.bottom:0,this.falling=!1;else if(a.yprop.isSlope&&!this.jumping)this.checkSlope(a.ytile,a.yprop.isLeftSlope),this.falling=!1;else{if(a.yprop.isBreakable)if(this.canBreakTile){if(me.game.currentLevel.clearTile(a.ytile.col,a.ytile.row),this.onTileBreak)this.onTileBreak()}else this.pos.y=~~this.pos.y,this.vel.y=this.falling?a.ytile.pos.y-this.collisionBox.bottom:0,this.falling=!1}else 0>a.y&&(!a.yprop.isPlatform&&!a.yprop.isLadder)&&
(this.falling=!0,this.vel.y=0);if(a.x)if(this.onladder=a.xprop.isLadder,a.xprop.isSlope&&!this.jumping)this.checkSlope(a.xtile,a.xprop.isLeftSlope),this.falling=!1;else if(!a.xprop.isPlatform&&!a.xprop.isLadder)if(a.xprop.isBreakable&&this.canBreakTile){if(me.game.currentLevel.clearTile(a.xtile.col,a.xtile.row),this.onTileBreak)this.onTileBreak()}else this.vel.x=0;this.pos.add(this.vel);return a},draw:function(a){this.parent(a);if(me.debug.renderHitBox){this.collisionBox.draw(a,"red");var c=~~(this.pos.x+
this.hWidth),b=~~(this.pos.y+this.hHeight);a.lineWidth=1;a.beginPath();a.moveTo(c,b);a.lineTo(c+~~(this.vel.x*this.hWidth),b+~~(this.vel.y*this.hHeight));a.stroke()}}});me.CollectableEntity=me.ObjectEntity.extend({init:function(a,c,b){this.parent(a,c,b);this.collidable=!0;this.type=me.game.COLLECTABLE_OBJECT}});me.InvisibleEntity=me.Rect.extend({GUID:null,z:0,collisionBox:null,init:function(a,c,b){this.parent(new me.Vector2d(a,c),b.width,b.height);this.collisionBox=new me.Rect(this.pos,b.width,b.height);
this.GUID=me.utils.createGUID();this.name=b.name?b.name.toLowerCase():"";this.isEntity=this.collidable=this.visible=!0},updateColRect:function(a,c,b,f){this.collisionBox.adjustSize(a,c,b,f)},onCollision:function(){},destroy:function(){this.onDestroyEvent.apply(this,arguments)},onDestroyEvent:function(){},update:function(){return!1},draw:function(a){me.debug.renderHitBox&&(a.strokeStyle="blue",a.strokeRect(this.pos.x,this.pos.y,this.width,this.height),this.collisionBox.draw(a))}});me.LevelEntity=me.InvisibleEntity.extend({init:function(a,
c,b){this.parent(a,c,b);this.nextlevel=b.to;this.fade=b.fade;this.duration=b.duration;this.fading=!1;this.gotolevel=b.to},onFadeComplete:function(){me.levelDirector.loadLevel(this.gotolevel);me.game.viewport.fadeOut(this.fade,this.duration)},goTo:function(a){this.gotolevel=a||this.nextlevel;this.fade&&this.duration?this.fading||(this.fading=!0,me.game.viewport.fadeIn(this.fade,this.duration,this.onFadeComplete.bind(this))):me.levelDirector.loadLevel(this.gotolevel)},onCollision:function(){this.goTo()}})})(window);
(function(){me.Font=Object.extend({ALIGN:{LEFT:"left",CENTER:"center",RIGHT:"right"},font:null,height:null,color:null,align:null,init:function(a,b,c,d){this.set(a,b,c,d)},bold:function(){this.font="bold "+this.font},italic:function(){this.font="italic "+this.font},set:function(a,b,c,d){this.font=""+b+"px '"+a+"'";this.height=b;this.color=c;this.align=d||"top"},getRect:function(){return new me.Rect(new Vector2d(0,0),0,0)},measureText:function(a,b){a.font=this.font;a.fillStyle=this.color;a.textBaseline=
this.align;var c=a.measureText(b);c.height=this.height;return c},draw:function(a,b,c,d){a.font=this.font;a.fillStyle=this.color;a.textBaseline=this.align;a.fillText(b,~~c,~~d)}});me.BitmapFont=me.Font.extend({size:null,sSize:null,firstChar:32,charCount:0,init:function(a,b,c,d){this.parent(a,null,null);this.size=new me.Vector2d;this.sSize=new me.Vector2d;this.firstChar=d||32;this.loadFontMetrics(a,b);this.align=this.ALIGN.RIGHT;c&&this.resize(c)},loadFontMetrics:function(a,b){this.font=me.loader.getImage(a);
this.size.x=b.x||b;this.size.y=b.y||this.font.height;this.sSize.copy(this.size);this.charCount=~~(this.font.width/this.size.x)},set:function(a,b){this.align=a;b&&this.resize(b)},resize:function(a){this.sSize.copy(this.size);this.sSize.x*=a;this.sSize.y*=a},measureText:function(a){return{width:a.length*this.sSize.x,height:this.sSize.y}},draw:function(a,b,c,d){b=new String(b);switch(this.align){case this.ALIGN.RIGHT:c-=this.measureText(b).width;break;case this.ALIGN.CENTER:c-=0.5*this.measureText(b).width}for(var e=
0,g=b.length;e<g;e++){var f=b.charCodeAt(e)-this.firstChar;a.drawImage(this.font,this.size.x*(f%this.charCount),this.size.y*~~(f/this.charCount),this.size.x,this.size.y,~~c,~~d,this.sSize.x,this.sSize.y);c+=this.sSize.x}}})})(window);
(function(){me.GUI_Object=me.SpriteObject.extend({isClickable:!0,updated:!1,init:function(a,b,c){this.parent(a,b,"string"==typeof c.image?me.loader.getImage(c.image):c.image,c.spritewidth,c.spriteheight);this.floating=!0;me.input.registerMouseEvent("mousedown",this,this.clicked.bind(this))},update:function(){return this.updated?(this.updated=!1,!0):!1},clicked:function(){if(this.isClickable)return this.updated=!0,this.onClick()},onClick:function(){return!0},onDestroyEvent:function(){me.input.releaseMouseEvent("mousedown",
this)}})})(window);
(function(){me.HUD_Item=Object.extend({init:function(a,b,c){this.pos=new me.Vector2d(a||0,b||0);this.visible=!0;this.defaultvalue=c||0;this.value=c||0;this.updated=!0},reset:function(){this.set(this.defaultvalue)},set:function(a){this.value=a;return this.updated=!0},update:function(a){return this.set(this.value+a)},draw:function(){}});me.HUD_Object=me.Rect.extend({init:function(a,b,c,d,e){this.parent(new me.Vector2d(a||0,b||0),c||me.video.getWidth(),d||me.video.getHeight());this.bgcolor=e;this.HUDItems=
{};this.HUDobj=[];this.objCount=0;this.HUD_invalidated=this.floating=this.visible=!0;this.HUDCanvas=me.video.createCanvas(this.width,this.height);this.HUDCanvasSurface=this.HUDCanvas.getContext("2d");this.z=999;this.isPersistent=!0},addItem:function(a,b){this.HUDItems[a]=b;this.HUDobj.push(this.HUDItems[a]);this.objCount++;this.HUD_invalidated=!0},removeItem:function(a){this.HUDItems[a]&&(this.HUDobj.splice(this.HUDobj.indexOf(this.HUDItems[a]),1),this.HUDItems[a]=null,this.objCount--,this.HUD_invalidated=
!0)},setItemValue:function(a,b){this.HUDItems[a]&&!0==this.HUDItems[a].set(b)&&(this.HUD_invalidated=!0)},updateItemValue:function(a,b){this.HUDItems[a]&&!0==this.HUDItems[a].update(b)&&(this.HUD_invalidated=!0)},getItemValue:function(a){return this.HUDItems[a]?this.HUDItems[a].value:0},update:function(){return this.HUD_invalidated},reset:function(a){void 0!=a?(this.HUDItems[a]&&this.HUDItems[a].reset(),this.HUD_invalidated=!0):this.resetAll()},resetAll:function(){for(var a=this.objCount,b;a--,b=
this.HUDobj[a];)b.reset();this.HUD_invalidated=!0},getRect:function(){p=this.pos.clone();p.add(me.game.viewport.pos);return new me.Rect(p,this.width,this.height)},draw:function(a){if(this.HUD_invalidated){this.bgcolor?me.video.clearSurface(this.HUDCanvasSurface,this.bgcolor):this.HUDCanvas.width=this.HUDCanvas.width;for(var b=this.objCount,c;b--,c=this.HUDobj[b];)c.visible&&(c.draw(this.HUDCanvasSurface,0,0),c.updated&&(c.updated=!1))}a.drawImage(this.HUDCanvas,this.pos.x,this.pos.y);this.HUD_invalidated=
!1}})})(window);
(function(){var a=me,b=function(a){for(var a=g[a],c=0,b;b=a[c++];)if(b.ended||!b.currentTime)return b.currentTime=k,b;a[0].pause();a[0].currentTime=k;return a[0]},c=function(a,c,d){var e=b(a.toLowerCase());e.loop=c||!1;e.play();d&&!c&&e.addEventListener("ended",function(a){e.removeEventListener("ended",arguments.callee,!1);d()},!1)},d=function(a,c,b){b&&!c&&setTimeout(b,2E3)},e={},g={},f=["mp3","ogg","wav"],j=null,l=-1,m=null,h=null,n=null,r=!0,k=0,t=0;e.capabilities={mp3:!1,ogg:!1,ma4:!1,wav:!1};
e.init=function(a){if(!me.initialized)throw"melonJS: me.audio.init() called before engine initialization.";j=a?new String(a):new String("mp3");var b=a="",g=null,h=0,m=f.length;if(me.sys.sound)for(;h<m;h++)if(b=f[h],g=RegExp(b,"i"),-1!=j.search(g)&&e.capabilities[b]){a=b;break}""===a&&(r=!1);l=a;e.play=r?c:d;return r};e.setLoadCallback=function(a){m=a};e.isAudioEnable=function(){return r};e.enable=function(){r=me.sys.sound;e.play=r?c:d};e.disable=function(){r=!1;e.play=d};e.load=function(a){if(-1==
l)return 0;var c=new Audio(a.src+a.name+"."+l+me.nocache);c.preload="auto";c.addEventListener("canplaythrough",function(c){this.removeEventListener("canplaythrough",arguments.callee,!1);var b=a.name,d=a.channel;t=0;if(1<d)for(var e=g[b][0],f=1;f<d;f++){var h=e.cloneNode(!0);0==h.currentSrc.length&&(h.src=e.src);g[b][f]=h;g[b][f].load()}m&&m()},!1);c.addEventListener("error",function(){var c=a.name;if(3<t++)if(c="melonJS: failed loading "+c+"."+l,!1===me.sys.stopOnAudioError)me.audio.disable(),m&&
m(),console.log(c+", disabling audio");else throw c;else g[c][0].load()},!1);c.src=a.src+a.name+"."+l+me.nocache;c.load();g[a.name]=[c];return 1};e.stop=function(a){if(r)for(var a=g[a.toLowerCase()],c=a.length;c--;)a[c].pause(),a[c].currentTime=k};e.pause=function(a){if(r)for(var a=g[a.toLowerCase()],c=a.length;c--;)a[c].pause()};e.playTrack=function(a){if(r&&(null!=n&&e.stopTrack(),a=a.toLowerCase(),n=b(a)))h=a,n.loop=!0,n.play()};e.stopTrack=function(){r&&n&&(n.pause(),n=h=null)};e.pauseTrack=function(){r&&
n&&n.pause()};e.resumeTrack=function(){r&&n&&n.play()};e.unload=function(a){a=a.toLowerCase();if(!(a in g))return!1;h===a?e.stopTrack():e.stop(a);delete g[a];return!0};e.unloadAll=function(){for(var a in g)e.unload(a)};a.audio=e})(window);
(function(){var a=me,b={},c=null,d=0,e=0,g=0,f=0,j=0,l=Math.ceil(1E3/me.sys.fps),m=1.25*(1E3/me.sys.fps);b.tick=1;b.fps=0;b.init=function(){c=document.getElementById("framecounter");null!==c&&(me.debug.displayFPS=!0);b.reset()};b.reset=function(){f=g=Date.now();d=e=0};b.getTime=function(){return f};b.update=function(){g=f;f=Date.now();j=f-g;me.debug.displayFPS&&(d++,e+=j,0==d%10&&(this.fps=(~~(1E3*d/e)).clamp(0,me.sys.fps),d=e=0),null!==c&&c.replaceChild(document.createTextNode("("+this.fps+"/"+me.sys.fps+
" fps)"),c.firstChild));b.tick=j>m&&me.sys.interpolation?j/l:1};a.timer=b;var a=me,h={},n=null,r=null,k=null,t=null,v=null,i=-1,w=!1,s=0,A=0,x=!1,u=!0;h.init=function(a,c,b,d,e,f){if(!me.initialized)throw"melonJS: me.video.init() called before engine initialization.";w=d||!1;x="auto"===e||!1;u=void 0!==f?f:!0;e="auto"!==e?parseFloat(e||1):1;me.sys.scale=new me.Vector2d(e,e);if(x||1!==e)w=!0;s=c*me.sys.scale.x;A=b*me.sys.scale.y;window.addEventListener("resize",function(a){me.event.publish(me.event.WINDOW_ONRESIZE,
[a])},!1);window.addEventListener("orientationchange",function(a){me.event.publish(me.event.WINDOW_ONRESIZE,[a])},!1);me.event.subscribe(me.event.WINDOW_ONRESIZE,me.video.onresize.bind(me.video));n=h.createCanvas(s,A);a&&(v=document.getElementById(a));v||(v=document.body);v.appendChild(n);if(!n.getContext)return!1;r=n.getContext("2d");w?(k=h.createCanvas(c,b),t=k.getContext("2d")):(k=n,t=r);if(x)me.video.onresize(null);return!0};h.getWrapper=function(){return v};h.getWidth=function(){return k.width};
h.getPos=function(a){for(var a=a||n,c=new me.Vector2d(a.offsetLeft,a.offsetTop);a=a.offsetParent;)c.x+=a.offsetLeft,c.y+=a.offsetTop;return c};h.getHeight=function(){return k.height};h.createCanvas=function(a,c){var b=document.createElement("canvas");b.width=a||k.width;b.height=c||k.height;return b};h.createCanvasSurface=function(a,c){return h.createCanvas(a,c).getContext("2d")};h.getScreenCanvas=function(){return n};h.getScreenFrameBuffer=function(){return t};h.onresize=function(){if(x){var a=me.video.getScreenCanvas().parentNode,
c=a.width||window.innerWidth,a=a.height||window.innerHeight;i&&clearTimeout(i);if(u){var b=me.video.getWidth()/me.video.getHeight(),c=c/a<b?c/me.video.getWidth():a/me.video.getHeight();i=me.video.updateDisplaySize.defer(c,c)}else i=me.video.updateDisplaySize.defer(c/me.video.getWidth(),a/me.video.getHeight())}else me.input.mouse.offset=me.video.getPos()};h.updateDisplaySize=function(a,c){me.sys.scale.set(a,c);n.width=s=k.width*a;n.height=A=k.height*c;me.input.mouse.offset=me.video.getPos();h.blitSurface();
i=-1};h.clearSurface=function(a,c){a.save();a.setTransform(1,0,0,1,0,0);a.fillStyle=c;a.fillRect(0,0,h.getWidth(),h.getHeight());a.restore()};h.scale=function(a,c){a.translate(-(a.canvas.width*c-a.canvas.width>>1),-(a.canvas.height*c-a.canvas.height>>1));a.scale(c,c)};h.setAlpha=function(a,c){a.globalCompositeOperation=c?"source-over":"copy"};h.blitSurface=function(){h.blitSurface=w?function(){r.drawImage(k,0,0,k.width,k.height,0,0,s,A)}:function(){};h.blitSurface()};h.applyRGBFilter=function(a,c,
b){var d=h.createCanvasSurface(a.width,a.height),a=me.utils.getPixels(a),e=a.data;switch(c){case "b&w":for(var c=0,f=e.length;c<f;c+=4)b=3*e[c]+4*e[c+1]+e[c+2]>>>3,e[c]=b,e[c+1]=b,e[c+2]=b;break;case "brightness":b=Math.abs(b).clamp(0,1);c=0;for(f=e.length;c<f;c+=4)e[c]*=b,e[c+1]*=b,e[c+2]*=b;break;case "transparent":c=0;for(f=e.length;c<f;c+=4)me.utils.RGBToHex(e[c],e[c+1],e[c+2])===b&&(e[c+3]=0);break;default:return null}d.putImageData(a,0,0);return d};a.video=h})(window);
(function(a){var b=me,c=function(){if(!A){k.touches.push({x:0,y:0});k.mouse.pos=new me.Vector2d(0,0);k.mouse.offset=me.video.getPos();if(me.sys.touch){me.video.getScreenCanvas().addEventListener("touchmove",m,!1);for(var c=2;c<B.length;++c)me.video.getScreenCanvas().addEventListener(B[c],n,!1)}else{me.video.getScreenCanvas().addEventListener("mousemove",m,!1);a.addEventListener("mousewheel",l,!1);for(c=2;c<u.length;++c)me.video.getScreenCanvas().addEventListener(u[c],h,!1)}A=!0}},d=function(a){a.stopPropagation?
a.stopPropagation():a.cancelBubble=!0;a.preventDefault?a.preventDefault():a.returnValue=!1;return!1},e=function(a,c){var b=t[c||a.keyCode||a.which];return b?(w[b]||(v[b]=!0,w[b]=i[b],me.event.publish(me.event.KEYDOWN,[b])),d(a)):!0},g=function(a,c){var b=t[c||a.keyCode||a.which];return b?(v[b]=!1,w[b]=!1,me.event.publish(me.event.KEYUP,[b]),d(a)):!0},f=function(a){var c=!1,b=k.mouse.handlers[a.type];if(b)for(var d=me.game.viewport.pos,e=me.game.currentLevel.pos,f=0,g=k.touches.length;f<g;f++)for(var h=
k.touches[f].x,m=k.touches[f].y,i=b.length,j;i--,j=b[i];){var r=!1===j.floating?{x:h+d.x-e.x,y:m+d.y-e.y}:{x:h,y:m};if((null===j.rect||j.rect.containsPoint(r))&&!1===j.cb(a)){c=!0;break}}return c},j=function(a){k.touches.length=0;if(a.touches)for(var c=k.mouse.offset,b=0,d=a.changedTouches.length;b<d;b++){var e=a.changedTouches[b],f=e.clientX-c.x,g=e.clientY-c.y,h=me.sys.scale;if(1!=h.x||1!=h.y)f/=h.x,g/=h.y;k.touches.push({x:f,y:g,id:e.identifier})}else{var c=k.mouse.offset,f=a.pageX-c.x,g=a.pageY-
c.y,h=me.sys.scale;if(1!=h.x||1!=h.y)f/=h.x,g/=h.y;k.touches.push({x:f,y:g,id:0})}k.mouse.pos.set(k.touches[0].x,k.touches[0].y)},l=function(a){return a.target==me.video.getScreenCanvas()&&f(a)?d(a):!0},m=function(a){j(a);return f(a)?d(a):!0},h=function(a){if(f(a))return d(a);var c=k.mouse.bind[a.button||0];return c?"mousedown"===a.type||"touchstart"===a.type?e(a,c):g(a,c):!0},n=function(a){j(a);return h(a)},r=function(a){k.accel=a.accelerationIncludingGravity},k={},t={},v={},i={},w={},s=!1,A=!1,
x=!1,u="mousewheel mousemove mousedown mouseup click dblclick".split(" "),B=[void 0,"touchmove","touchstart","touchend","tap","dbltap"];k.accel={x:0,y:0,z:0};k.mouse={pos:null,offset:null,LEFT:0,MIDDLE:1,RIGHT:2,bind:[0,0,0],handlers:{}};k.touches=[];k.KEY={LEFT:37,UP:38,RIGHT:39,DOWN:40,ENTER:13,SHIFT:16,CTRL:17,ALT:18,PAUSE:19,ESC:27,SPACE:32,NUM0:48,NUM1:49,NUM2:50,NUM3:51,NUM4:52,NUM5:53,NUM6:54,NUM7:55,NUM8:56,NUM9:57,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75,L:76,M:77,N:78,O:79,
P:80,Q:81,R:82,S:83,T:84,U:85,V:86,W:87,X:88,Y:89,Z:90};k.isKeyPressed=function(a){return v[a]?(i[a]&&(w[a]=!0,v[a]=!1),!0):!1};k.keyStatus=function(a){return!0===w[a]?!0:v[a]};k.triggerKeyEvent=function(a,c){c?e({},a):g({},a)};k.bindKey=function(c,b,d){s||(a.addEventListener("keydown",e,!1),a.addEventListener("keyup",g,!1),s=!0);t[c]=b;v[b]=!1;i[b]=d?d:!1;w[b]=!1};k.unbindKey=function(a){v[t[a]]=!1;i[t[a]]=!1;t[a]=null};k.bindMouse=function(a,b){c();if(!t[b])throw"melonJS : no action defined for keycode "+
b;k.mouse.bind[a]=b};k.unbindMouse=function(a){k.mouse.bind[a]=null};k.bindTouch=function(a){k.bindMouse(me.input.mouse.LEFT,a)};k.unbindTouch=function(){k.unbindMouse(me.input.mouse.LEFT)};k.registerMouseEvent=function(a,b,d,e){c();me.sys.touch&&-1!==u.indexOf(a)&&(a=B[u.indexOf(a)]);if(a&&(-1!==u.indexOf(a)||-1!==B.indexOf(a))){k.mouse.handlers[a]||(k.mouse.handlers[a]=[]);var f=!0===b.floating?!0:!1;e&&(f=!0===e?!0:!1);k.mouse.handlers[a].push({rect:b||null,cb:d,floating:f})}else throw"melonJS : invalid event type : "+
a;};k.releaseMouseEvent=function(a,c){me.sys.touch&&-1!==u.indexOf(a)&&(a=B[u.indexOf(a)]);if(a&&(-1!==u.indexOf(a)||-1!==B.indexOf(a))){k.mouse.handlers[a]||(k.mouse.handlers[a]=[]);var b=k.mouse.handlers[a];if(b)for(var d=b.length,e;d--,e=b[d];)e.rect===c&&(e.rect=e.cb=e.floating=null,k.mouse.handlers[a].splice(d,1))}else throw"melonJS : invalid event type : "+a;};k.watchAccelerometer=function(){return a.sys.gyro?(x||(a.addEventListener("devicemotion",r,!1),x=!0),!0):!1};k.unwatchAccelerometer=
function(){x&&(a.removeEventListener("devicemotion",r,!1),x=!1)};b.input=k})(window);
(function(a){var b={decode:function(c){c=c.replace(/[^A-Za-z0-9\+\/\=]/g,"");if(me.sys.nativeBase64)return a.atob(c);for(var b=[],d,e,f,g,j,i=0;i<c.length;)d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(c.charAt(i++)),e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(c.charAt(i++)),g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(c.charAt(i++)),j="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(c.charAt(i++)),
d=d<<2|e>>4,e=(e&15)<<4|g>>2,f=(g&3)<<6|j,b.push(String.fromCharCode(d)),64!=g&&b.push(String.fromCharCode(e)),64!=j&&b.push(String.fromCharCode(f));return b=b.join("")}},c=me,d={},e={},g="",f=0,j=/^.*(\\|\/|\:)/,l=/\.[^\.]*$/;d.decodeBase64=function(a){return b.decode(a)};d.decodeBase64AsArray=function(a,c){var c=c||1,d=b.decode(a),e=[],f,g,j;f=0;for(j=d.length/c;f<j;f++){e[f]=0;for(g=c-1;0<=g;--g)e[f]+=d.charCodeAt(f*c+g)<<(g<<3)}return e};d.decodeCSV=function(a,c){for(var a=a.trim().split("\n"),
b=[],d=0;d<a.length;d++){entries=a[d].split(",",c);for(var e=0;e<entries.length;e++)b.push(+entries[e])}return b};d.getBasename=function(a){return a.replace(j,"").replace(l,"")};d.setNocache=function(a){me.nocache=a?"?"+parseInt(1E7*Math.random()):""};d.HexToRGB=function(a,c){if("#"!==a.charAt(0))return a;a=a.substring(1,a.length);if(null==e[a]){if(6>a.length)var b=a.charAt(0)+a.charAt(0),d=a.charAt(1)+a.charAt(1),f=a.charAt(2)+a.charAt(2);else b=a.substring(0,2),d=a.substring(2,4),f=a.substring(4,
6);e[a]=parseInt(b,16)+","+parseInt(d,16)+","+parseInt(f,16)}return(c?"rgba(":"rgb(")+e[a]+(c?","+c+")":")")};d.RGBToHex=function(a,c,b){return a.toHex()+c.toHex()+b.toHex()};d.getPixels=function(a){if(a instanceof HTMLImageElement){var c=me.video.createCanvasSurface(a.width,a.height);c.drawImage(a,0,0);return c.getImageData(0,0,a.width,a.height)}return a.getContext("2d").getImageData(0,0,a.width,a.height)};d.resetGUID=function(a){g=a.toString().toUpperCase().toHex();f=0};d.createGUID=function(){return g+
"-"+f++};d.applyFriction=function(a,c){return 0>a+c?a+c*me.timer.tick:0<a-c?a-c*me.timer.tick:0};c.utils=d})(window);
(function(){function a(a){this.defaultvalue=a||0;this.value=a||0;this.updated=!0}a.prototype.reset=function(){this.set(this.defaultvalue)};a.prototype.update=function(a){return this.set(this.value+a)};a.prototype.set=function(a){this.value=a;return this.updated=!0};var b=me,c={},d={},e=[],g=0;c.add=function(c,b){if(c.constructor===Object)for(var l in c){var m=l;d[m]=new a(c[l]);e.push(d[m]);g++}else d[c]=new a(b),e.push(d[c]),g++};c.updateValue=function(a,c){if(a.constructor===Object)for(var b in a)d[b]&&
d[b].update(a[b]);else d[a]&&d[a].update(c)};c.setValue=function(a,c){if(a.constructor===Object)for(var b in a)d[b]&&d[b].set(a[b]);else d[a]&&d[a].set(c)};c.getItemValue=function(a){return d[a]?d[a].value:0};c.reset=function(a){void 0!=a?d[a]&&d[a].reset():c.resetAll()};c.resetAll=function(){for(var a=g,c;a--,c=e[a];)c.reset()};b.gamestat=c})(window);
(function(){me.LevelConstants={COLLISION_MAP:"collision",PARALLAX_MAP:"parallax"};me.TMX_TAG_MAP="map";me.TMX_TAG_NAME="name";me.TMX_TAG_VALUE="value";me.TMX_TAG_VERSION="version";me.TMX_TAG_ORIENTATION="orientation";me.TMX_TAG_WIDTH="width";me.TMX_TAG_HEIGHT="height";me.TMX_TAG_OPACITY="opacity";me.TMX_TAG_TRANS="trans";me.TMX_TAG_TILEWIDTH="tilewidth";me.TMX_TAG_TILEHEIGHT="tileheight";me.TMX_TAG_TILEOFFSET="tileoffset";me.TMX_TAG_FIRSTGID="firstgid";me.TMX_TAG_GID="gid";me.TMX_TAG_TILE="tile";
me.TMX_TAG_ID="id";me.TMX_TAG_DATA="data";me.TMX_TAG_COMPRESSION="compression";me.TMX_TAG_ENCODING="encoding";me.TMX_TAG_ATTR_BASE64="base64";me.TMX_TAG_CSV="csv";me.TMX_TAG_SPACING="spacing";me.TMX_TAG_MARGIN="margin";me.TMX_TAG_PROPERTIES="properties";me.TMX_TAG_PROPERTY="property";me.TMX_TAG_IMAGE="image";me.TMX_TAG_SOURCE="source";me.TMX_TAG_VISIBLE="visible";me.TMX_TAG_TILESET="tileset";me.TMX_TAG_LAYER="layer";me.TMX_TAG_IMAGE_LAYER="imagelayer";me.TMX_TAG_OBJECTGROUP="objectgroup";me.TMX_TAG_OBJECT=
"object";me.TMX_TAG_X="x";me.TMX_TAG_Y="y";me.TMX_TAG_WIDTH="width";me.TMX_TAG_HEIGHT="height";me.TMX_TAG_POLYGON="polygon";me.TMX_TAG_POLYLINE="polyline";me.TMX_TAG_POINTS="points";me.TMX_BACKGROUND_COLOR="backgroundcolor"})(window);
(function(){me.TMXUtils={setTMXProperties:function(a,b){var c=b.getElementsByTagName(me.TMX_TAG_PROPERTIES)[0];if(c)for(var c=c.getElementsByTagName(me.TMX_TAG_PROPERTY),d=0;d<c.length;d++){var e=me.XMLParser.getStringAttribute(c[d],me.TMX_TAG_NAME),g=me.XMLParser.getStringAttribute(c[d],me.TMX_TAG_VALUE);!g||g.isBoolean()?g=g?"true"==g:!0:g.isNumeric()&&(g=Number(g));a[e]=g}},mergeProperties:function(a,b,c){for(var d in b)if(c||void 0===a[d])a[d]=b[d];return a}}})(window);
(function(){me.TMXOBjectGroup=Object.extend({init:function(a,b,c,d){this.objects=[];this.name=a;this.width=me.XMLParser.getIntAttribute(b,me.TMX_TAG_WIDTH);this.height=me.XMLParser.getIntAttribute(b,me.TMX_TAG_HEIGHT);this.visible=1==me.XMLParser.getIntAttribute(b,me.TMX_TAG_VISIBLE,1);this.z=d;b.firstChild&&b.firstChild.nextSibling.nodeName===me.TMX_TAG_PROPERTIES&&me.TMXUtils.setTMXProperties(this,b);a=b.getElementsByTagName(me.TMX_TAG_OBJECT);for(b=0;b<a.length;b++)this.objects.push(new me.TMXOBject(a[b],
c,d))},reset:function(){this.objects=null},getObjectCount:function(){return this.objects.length},getObjectByIndex:function(a){return this.objects[a]}});me.TMXOBject=Object.extend({init:function(a,b,c){this.name=me.XMLParser.getStringAttribute(a,me.TMX_TAG_NAME);this.x=me.XMLParser.getIntAttribute(a,me.TMX_TAG_X);this.y=me.XMLParser.getIntAttribute(a,me.TMX_TAG_Y);this.z=c;this.width=me.XMLParser.getIntAttribute(a,me.TMX_TAG_WIDTH,0);this.height=me.XMLParser.getIntAttribute(a,me.TMX_TAG_HEIGHT,0);
if(this.gid=me.XMLParser.getIntAttribute(a,me.TMX_TAG_GID,null))b=b.getTilesetByGid(this.gid),this.width=b.tilewidth,this.height=b.tileheight,this.spritewidth=this.width,this.y-=this.height,c=new me.Tile(this.x,this.y,b.tilewidth,b.tileheight,this.gid),this.image=b.getTileImage(c);else if(b=a.getElementsByTagName(me.TMX_TAG_POLYGON),this.isPolygon=!0,b.length||(b=a.getElementsByTagName(me.TMX_TAG_POLYLINE),this.isPolygon=!1),b.length){this.points=[];for(var b=me.XMLParser.getStringAttribute(b[0],
me.TMX_TAG_POINTS).split(" "),c=0,d;c<b.length;c++)d=b[c].split(","),this.points[c]=new me.Vector2d(+d[0],+d[1])}me.TMXUtils.setTMXProperties(this,a)},getObjectPropertyByName:function(a){return this[a]}})})(window);
(function(){me.Tile=me.Rect.extend({tileId:null,init:function(a,b,c,d,e){this.parent(new me.Vector2d(a*c,b*d),c,d);this.col=a;this.row=b;this.tileId=e;this.flipX=0!==(this.tileId&2147483648);this.flipY=0!==(this.tileId&1073741824);this.flipAD=0!==(this.tileId&536870912);this.flipped=this.flipX||this.flipY||this.flipAD;this.tileId&=536870911}});me.Tileset=Object.extend({init:function(a,b,c,d,e,g){this.name=a;this.tilewidth=b;this.tileheight=c;this.spacing=d;this.margin=e;(this.image=g?me.loader.getImage(me.utils.getBasename(g)):
null)||console.log("melonJS: '"+g+"' file for tileset '"+this.name+"' not found!");this.type={SOLID:"solid",PLATFORM:"platform",L_SLOPE:"lslope",R_SLOPE:"rslope",LADDER:"ladder",BREAKABLE:"breakable"};this.TileProperties=[];this.tileXOffset=[];this.tileYOffset=[];this.image&&(this.hTileCount=~~((this.image.width-this.margin)/(this.tilewidth+this.spacing)),this.vTileCount=~~((this.image.height-this.margin)/(this.tileheight+this.spacing)))},getPropertyList:function(){return{isCollidable:!1,isSolid:!1,
isPlatform:!1,isSlope:!1,isLeftSlope:!1,isRightSlope:!1,isLadder:!1,isBreakable:!1}},getTileProperties:function(a){return this.TileProperties[a]},isTileCollidable:function(a){return this.TileProperties[a].isCollidable},getTileOffsetX:function(a){null==this.tileXOffset[a]&&(this.tileXOffset[a]=this.margin+(this.spacing+this.tilewidth)*(a%this.hTileCount));return this.tileXOffset[a]},getTileOffsetY:function(a){null==this.tileYOffset[a]&&(this.tileYOffset[a]=this.margin+(this.spacing+this.tileheight)*
~~(a/this.hTileCount));return this.tileYOffset[a]}});me.TMXTileset=me.Tileset.extend({init:function(a){this.firstgid=me.XMLParser.getIntAttribute(a,me.TMX_TAG_FIRSTGID);var b=me.XMLParser.getStringAttribute(a,me.TMX_TAG_SOURCE);if(b){b=me.utils.getBasename(b);a=me.loader.getXML(b);if(!a)throw"melonJS:"+b+" TSX tileset not found";me.XMLParser.parseFromString(a);a=me.XMLParser.getFirstElementByTagName("tileset")}this.parent(me.XMLParser.getStringAttribute(a,me.TMX_TAG_NAME),me.XMLParser.getIntAttribute(a,
me.TMX_TAG_TILEWIDTH),me.XMLParser.getIntAttribute(a,me.TMX_TAG_TILEHEIGHT),me.XMLParser.getIntAttribute(a,me.TMX_TAG_SPACING,0),me.XMLParser.getIntAttribute(a,me.TMX_TAG_MARGIN,0),a.getElementsByTagName(me.TMX_TAG_IMAGE)[0].getAttribute(me.TMX_TAG_SOURCE));this.lastgid=this.firstgid+(this.hTileCount*this.vTileCount-1||0);this.trans=a.getElementsByTagName(me.TMX_TAG_IMAGE)[0].getAttribute(me.TMX_TAG_TRANS);null!==this.trans&&this.image&&(this.image=me.video.applyRGBFilter(this.image,"transparent",
this.trans.toUpperCase()).canvas);this.tileoffset=new me.Vector2d(0,0);b=a.getElementsByTagName(me.TMX_TAG_TILEOFFSET);0<b.length&&(this.tileoffset.x=me.XMLParser.getIntAttribute(b[0],me.TMX_TAG_X),this.tileoffset.y=me.XMLParser.getIntAttribute(b[0],me.TMX_TAG_Y));a=a.getElementsByTagName(me.TMX_TAG_TILE);for(b=0;b<a.length;b++){var c=me.XMLParser.getIntAttribute(a[b],me.TMX_TAG_ID)+this.firstgid;this.TileProperties[c]={};c=this.TileProperties[c];me.TMXUtils.setTMXProperties(c,a[b]);c.isSolid=c.type?
c.type.toLowerCase()===this.type.SOLID:!1;c.isPlatform=c.type?c.type.toLowerCase()===this.type.PLATFORM:!1;c.isLeftSlope=c.type?c.type.toLowerCase()===this.type.L_SLOPE:!1;c.isRightSlope=c.type?c.type.toLowerCase()===this.type.R_SLOPE:!1;c.isBreakable=c.type?c.type.toLowerCase()===this.type.BREAKABLE:!1;c.isLadder=c.type?c.type.toLowerCase()===this.type.LADDER:!1;c.isSlope=c.isLeftSlope||c.isRightSlope;c.isCollidable=c.isSolid||c.isPlatform||c.isSlope||c.isLadder||c.isBreakable}},contains:function(a){return a>=
this.firstgid&&a<=this.lastgid},getTileImage:function(a){var b=me.video.createCanvasSurface(this.tilewidth,this.tileheight);this.drawTile(b,0,0,a);return b.canvas},drawTile:function(a,b,c,d){if(d.flipped){var e=1,g=0,f=0,j=1,l=b,m=c,b=c=0;a.save();d.flipAD&&(e=0,f=g=1,j=0,m+=this.tileheight-this.tilewidth);d.flipX&&(e=-e,f=-f,l+=d.flipAD?this.tileheight:this.tilewidth);d.flipY&&(g=-g,j=-j,m+=d.flipAD?this.tilewidth:this.tileheight);a.transform(e,g,f,j,l,m)}e=d.tileId-this.firstgid;a.drawImage(this.image,
this.getTileOffsetX(e),this.getTileOffsetY(e),this.tilewidth,this.tileheight,b,c,this.tilewidth,this.tileheight);d.flipped&&a.restore()}});me.TMXTilesetGroup=Object.extend({init:function(){this.tilesets=[]},add:function(a){this.tilesets.push(a)},getTilesetByIndex:function(a){return this.tilesets[a]},getTilesetByGid:function(a){for(var b=-1,c=0,d=this.tilesets.length;c<d;c++){if(this.tilesets[c].contains(a))return this.tilesets[c];this.tilesets[c].firstgid==this.tilesets[c].lastgid&&a>=this.tilesets[c].firstgid&&
(b=c)}if(-1!=b)return this.tilesets[b];throw"no matching tileset found for gid "+a;}})})(window);
(function(){me.TMXOrthogonalRenderer=Object.extend({init:function(a,b,c,d){this.width=a;this.height=b;this.tilewidth=c;this.tileheight=d},pixelToTileCoords:function(a,b){return new me.Vector2d(a/this.tilewidth,b/this.tileheight)},tileToPixelCoords:function(a,b){return new me.Vector2d(a*this.tilewidth,b*this.tileheight)},drawTile:function(a,b,c,d,e){e.drawTile(a,e.tileoffset.x+b*this.tilewidth,e.tileoffset.y+(c+1)*this.tileheight-e.tileheight,d)},drawTileLayer:function(a,b,c,d){var e=this.pixelToTileCoords(c.x+
d.pos.x,c.y+d.pos.y).floorSelf(),c=this.pixelToTileCoords(c.x+d.pos.x+d.width+this.tilewidth,c.y+d.pos.y+d.height+this.tileheight).ceilSelf();c.x=c.x>this.width?this.width:c.x;c.y=c.y>this.height?this.height:c.y;for(d=e.y;d<c.y;d++)for(var g=e.x;g<c.x;g++){var f=b.layerData[g][d];f&&(b.tileset.contains(f.tileId)||(b.tileset=b.tilesets.getTilesetByGid(f.tileId)),this.drawTile(a,g,d,f,b.tileset))}}});me.TMXIsometricRenderer=Object.extend({init:function(a,b,c,d){this.width=a;this.height=b;this.tilewidth=
c;this.tileheight=d;this.hTilewidth=c/2;this.hTileheight=d/2;this.ratio=this.tilewidth/this.tileheight;this.originX=this.height*this.hTilewidth},pixelToTileCoords:function(a,b){a-=this.originX;return new me.Vector2d((b+a/this.ratio)/this.tileheight,(b-a/this.ratio)/this.tileheight)},tileToPixelCoords:function(a,b){return new me.Vector2d((a-b)*this.hTilewidth+this.originX,(a+b)*this.hTileheight)},drawTile:function(a,b,c,d,e){e.drawTile(a,(this.width-1)*e.tilewidth+(b-c)*e.tilewidth>>1,-e.tilewidth+
(b+c)*e.tileheight>>2,d)},drawTileLayer:function(a,b,c,d){var e=b.tileset,g=e.tileoffset,f=this.pixelToTileCoords(c.x+d.pos.x-e.tilewidth,c.y+d.pos.y-e.tileheight).floorSelf(),j=this.pixelToTileCoords(c.x+d.pos.x+d.width+e.tilewidth,c.y+d.pos.y+d.height+e.tileheight).ceilSelf(),j=this.tileToPixelCoords(j.x,j.y),l=this.tileToPixelCoords(f.x,f.y);l.x-=this.hTilewidth;l.y+=this.tileheight;var m=l.y-d.pos.y+c.y>this.hTileheight,c=d.pos.x+c.x-l.x<this.hTilewidth;m&&(c?(f.x--,l.x-=this.hTilewidth):(f.y--,
l.x+=this.hTilewidth),l.y-=this.hTileheight);c^=m;d=f.clone();for(m=l.y;m-this.tileheight<j.y;m+=this.hTileheight){d.setV(f);for(var h=l.x;h<j.x;h+=this.tilewidth){if(0<=d.x&&0<=d.y&&d.x<this.width&&d.y<this.height){var n=b.layerData[d.x][d.y];n&&(e.contains(n.tileId)||(e=b.tileset=b.tilesets.getTilesetByGid(n.tileId),g=e.tileoffset),e.drawTile(a,g.x+h,g.y+m-e.tileheight,n))}d.x++;d.y--}c?(f.y++,l.x-=this.hTilewidth,c=!1):(f.x++,l.x+=this.hTilewidth,c=!0)}}})})(window);
(function(a,b){me.ColorLayer=Object.extend({init:function(a,b,e){this.name=a;this.color=me.utils.HexToRGB(b);this.z=e;this.visible=!0;this.opacity=1;this.floating=!0},reset:function(){},getOpacity:function(){return this.opacity},setOpacity:function(a){a&&(this.opacity=a.clamp(0,1))},update:function(){return!1},draw:function(a,b){var e=a.globalAlpha;a.globalAlpha=this.opacity;a.fillStyle=this.color;a.fillRect(b.left,b.top,b.width,b.height);a.globalAlpha=e}});me.ImageLayer=Object.extend({init:function(a,
d,e,g,f,j){this.name=a;(this.image=g?me.loader.getImage(me.utils.getBasename(g)):null)||console.log("melonJS: '"+g+"' file for Image Layer '"+this.name+"' not found!");this.imagewidth=this.image.width;this.imageheight=this.image.height;this.z=f;this.ratio=j||1;this.lastpos=b.viewport.pos.clone();this.offset=new me.Vector2d(0,0);this.width=d?Math.min(b.viewport.width,d):b.viewport.width;this.height=e?Math.min(b.viewport.height,e):b.viewport.height;this.visible=!0;this.opacity=1;this.floating=!0},reset:function(){this.offset=
this.viewport=this.lastpos=this.image=null},getOpacity:function(){return this.opacity},setOpacity:function(a){a&&(this.opacity=a.clamp(0,1))},update:function(){if(0!==this.ratio){var a=b.viewport.pos;if(!this.lastpos.equals(a))return this.offset.x=(this.imagewidth+this.offset.x+(a.x-this.lastpos.x)*this.ratio)%this.imagewidth,this.offset.y=(this.imageheight+this.offset.y+(a.y-this.lastpos.y)*this.ratio)%this.imageheight,this.lastpos.setV(a),!0}return!1},draw:function(a,b){if(1>this.opacity){var e=
a.globalAlpha;a.globalAlpha=this.opacity}if(0===this.ratio)m=Math.min(b.width,this.imagewidth),h=Math.min(b.height,this.imageheight),a.drawImage(this.image,b.left,b.top,m,h,b.left,b.top,m,h);else{var g=~~this.offset.x,f=~~this.offset.y,j=0,l=0,m=Math.min(this.imagewidth-~~this.offset.x,this.width),h=Math.min(this.imageheight-~~this.offset.y,this.height);do{do a.drawImage(this.image,g,f,m,h,j,l,m,h),f=0,l+=h,h=Math.min(this.imageheight,this.height-l);while(l<this.height);j+=m;if(j>=this.width)break;
g=0;m=Math.min(this.imagewidth,this.width-j);f=~~this.offset.y;l=0;h=Math.min(this.imageheight-~~this.offset.y,this.height)}while(1)}1>this.opacity&&(a.globalAlpha=e)}});CollisionTiledLayer=Object.extend({init:function(a,b){this.realwidth=a;this.realheight=b;this.isCollisionMap=!0},reset:function(){},checkCollision:function(a,b){var e=0>b.x?a.left+b.x:a.right+b.x,g=0>b.y?a.top+b.y:a.bottom+b.y,f={x:0,y:0,xprop:{},yprop:{}};if(0>=e||e>=this.realwidth)f.x=b.x;if(0>=g||g>=this.realheight)f.y=b.y;return f}});
me.TiledLayer=Object.extend({init:function(a,b,e,g,f,j){this.width=a;this.height=b;this.tilewidth=e;this.tileheight=g;this.realwidth=this.width*this.tilewidth;this.realheight=this.height*this.tileheight;this.z=j;this.name=null;this.visible=!1;this.opacity=1;this.layerData=null;this.tileset=(this.tilesets=f)?this.tilesets.getTilesetByIndex(0):null},reset:function(){this.tilesets=this.tileset=this.layerData=null},initArray:function(){this.layerData=[];for(var a=0;a<this.width;a++){this.layerData[a]=
[];for(var b=0;b<this.height;b++)this.layerData[a][b]=null}},getOpacity:function(){return this.opacity},setOpacity:function(a){a&&(this.opacity=a.clamp(0,1))},getTileId:function(a,b){var e=this.getTile(a,b);return e?e.tileId:null},getTile:function(a,b){return this.layerData[~~(a/this.tilewidth)][~~(b/this.tileheight)]},setTile:function(a,b,e){this.layerData[a][b]=new me.Tile(a,b,this.tilewidth,this.tileheight,e)},clearTile:function(a,b){this.layerData[a][b]=null},checkCollision:function(a,b){var e=
0>b.x?~~(a.left+b.x):Math.ceil(a.right-1+b.x),g=0>b.y?~~(a.top+b.y):Math.ceil(a.bottom-1+b.y),f={x:0,xtile:void 0,xprop:{},y:0,ytile:void 0,yprop:{}};0>=e||e>=this.realwidth?f.x=b.x:0!=b.x&&(f.xtile=this.getTile(e,Math.ceil(a.bottom-1)),f.xtile&&this.tileset.isTileCollidable(f.xtile.tileId)?(f.x=b.x,f.xprop=this.tileset.getTileProperties(f.xtile.tileId)):(f.xtile=this.getTile(e,~~a.top),f.xtile&&this.tileset.isTileCollidable(f.xtile.tileId)&&(f.x=b.x,f.xprop=this.tileset.getTileProperties(f.xtile.tileId))));
0!=b.y&&(f.ytile=this.getTile(0>b.x?~~a.left:Math.ceil(a.right-1),g),f.ytile&&this.tileset.isTileCollidable(f.ytile.tileId)?(f.y=b.y||1,f.yprop=this.tileset.getTileProperties(f.ytile.tileId)):(f.ytile=this.getTile(0>b.x?Math.ceil(a.right-1):~~a.left,g),f.ytile&&this.tileset.isTileCollidable(f.ytile.tileId)&&(f.y=b.y||1,f.yprop=this.tileset.getTileProperties(f.ytile.tileId))));return f},update:function(){return!1}});me.TMXLayer=me.TiledLayer.extend({init:function(a,b,e,g,f,j){this.parent(me.XMLParser.getIntAttribute(a,
me.TMX_TAG_WIDTH),me.XMLParser.getIntAttribute(a,me.TMX_TAG_HEIGHT),b,e,f,j);this.orientation=g;this.name=me.XMLParser.getStringAttribute(a,me.TMX_TAG_NAME);this.visible=1==me.XMLParser.getIntAttribute(a,me.TMX_TAG_VISIBLE,1);this.opacity=me.XMLParser.getFloatAttribute(a,me.TMX_TAG_OPACITY,1).clamp(0,1);me.TMXUtils.setTMXProperties(this,a);void 0===this.preRender&&(this.preRender=me.sys.preRender);if((this.isCollisionMap=this.name.toLowerCase().contains(me.LevelConstants.COLLISION_MAP))&&!me.debug.renderCollisionMap)this.visible=
!1;a=a.getElementsByTagName(me.TMX_TAG_DATA)[0];b=me.XMLParser.getStringAttribute(a,me.TMX_TAG_ENCODING,null);e=me.XMLParser.getStringAttribute(a,me.TMX_TAG_COMPRESSION,null);""==b&&(b=null);""==e&&(e=null);if(this.visible){switch(this.orientation){case "orthogonal":this.renderer=new me.TMXOrthogonalRenderer(this.width,this.height,this.tilewidth,this.tileheight);break;case "isometric":this.renderer=new me.TMXIsometricRenderer(this.width,this.height,this.tilewidth,this.tileheight);break;default:throw"melonJS: "+
this.orientation+" type TMX Tile Map not supported!";}this.preRender&&(this.layerCanvas=me.video.createCanvas(this.width*this.tilewidth,this.height*this.tileheight),this.layerSurface=this.layerCanvas.getContext("2d"),this.layerSurface.globalAlpha=this.opacity)}if(this.visible||this.isCollisionMap)this.initArray(),this.fillArray(a,b,e)},reset:function(){this.preRender&&(this.layerSurface=this.layerCanvas=null);this.renderer=null;this.parent()},fillArray:function(a,b,e){switch(e){case null:switch(b){case null:a=
a.getElementsByTagName(me.TMX_TAG_TILE);break;case me.TMX_TAG_CSV:case me.TMX_TAG_ATTR_BASE64:for(var e="",g=0,f=a.childNodes.length;g<f;g++)e+=a.childNodes[g].nodeValue;a=b==me.TMX_TAG_ATTR_BASE64?me.utils.decodeBase64AsArray(e,4):me.utils.decodeCSV(e,this.width);break;default:throw"melonJS: TMX Tile Map "+b+" encoding not supported!";}break;default:throw"melonJS: "+e+" compressed TMX Tile Map not supported!";}for(g=e=0;g<this.height;g++)for(f=0;f<this.width;f++){var j=null==b?me.XMLParser.getIntAttribute(a[e++],
me.TMX_TAG_GID):a[e++];0!==j&&(j=new me.Tile(f,g,this.tilewidth,this.tileheight,j),this.layerData[f][g]=j,this.tileset.contains(j.tileId)||(this.tileset=this.tilesets.getTilesetByGid(j.tileId)),this.visible&&this.preRender&&this.renderer.drawTile(this.layerSurface,f,g,j,this.tileset))}},clearTile:function(a,b){this.parent(a,b);this.visible&&this.preRender&&this.layerSurface.clearRect(a*this.tilewidth,b*this.tileheight,this.tilewidth,this.tileheight)},setOpacity:function(a){this.parent(a);this.preRender&&
(this.layerSurface.globalAlpha=this.opacity)},draw:function(a,d){var e=b.viewport.pos;if(this.preRender){var g=Math.min(d.width,this.realwidth),f=Math.min(d.height,this.realheight);a.drawImage(this.layerCanvas,e.x+d.pos.x,e.y+d.pos.y,g,f,d.pos.x,d.pos.y,g,f)}else g=a.globalAlpha,a.globalAlpha=this.opacity,this.renderer.drawTileLayer(a,this,e,d),a.globalAlpha=g}})})(window,me.game);
(function(){me.TileMap=Object.extend({init:function(a,b){this.pos=new me.Vector2d(a,b);this.z=0;this.name=null;this.height=this.width=0;this.realheight=this.realwidth=-1;this.tileheight=this.tilewidth=0;this.tilesets=null;this.mapLayers=[];this.objectGroups=[];this.initialized=!1},reset:function(){this.tilesets=null;this.mapLayers.length=0;this.objectGroups.length=0;this.pos.set(0,0);this.initialized=!1},getObjectGroupByName:function(a){return this.objectGroups[a]},getObjectGroups:function(){return this.objectGroups},
getLayers:function(){return this.mapLayers},getLayerByName:function(a){for(var b=null,a=a.trim().toLowerCase(),c=this.mapLayers.length;c--;)if(this.mapLayers[c].name.toLowerCase().contains(a)){b=this.mapLayers[c];break}a.toLowerCase().contains(me.LevelConstants.COLLISION_MAP)&&null==b&&(b=new CollisionTiledLayer(me.game.currentLevel.realwidth,me.game.currentLevel.realheight));return b},clearTile:function(a,b){for(var c=this.mapLayers.length;c--;)this.mapLayers[c].visible&&this.mapLayers[c]instanceof
me.TiledLayer&&this.mapLayers[c].clearTile(a,b)}});me.TMXTileMap=me.TileMap.extend({init:function(a,b,c){this.parent(b,c);this.xmlMap=me.loader.getXML(a);if(!this.xmlMap)throw"melonJS:"+a+" TMX map not found";this.orientation=this.version="";this.tilesets=null},reset:function(){if(!0===this.initialized){for(var a=this.mapLayers.length;a--;)this.mapLayers[a].reset(),this.mapLayers[a]=null;for(a=this.objectGroups.length;a--;)this.objectGroups[a].reset(),this.objectGroups[a]=null;this.parent();this.initialized=
!1}},load:function(){if(!this.initialized){var a=0,b=0.25;me.XMLParser.parseFromString(this.xmlMap);for(var c=me.XMLParser.getAllTagElements(),d=0;d<c.length;d++)switch(c.item(d).nodeName){case me.TMX_TAG_MAP:var e=c.item(d);this.version=me.XMLParser.getStringAttribute(e,me.TMX_TAG_VERSION);this.orientation=me.XMLParser.getStringAttribute(e,me.TMX_TAG_ORIENTATION);this.width=me.XMLParser.getIntAttribute(e,me.TMX_TAG_WIDTH);this.height=me.XMLParser.getIntAttribute(e,me.TMX_TAG_HEIGHT);this.tilewidth=
me.XMLParser.getIntAttribute(e,me.TMX_TAG_TILEWIDTH);this.tileheight=me.XMLParser.getIntAttribute(e,me.TMX_TAG_TILEHEIGHT);this.realwidth=this.width*this.tilewidth;this.realheight=this.height*this.tileheight;this.backgroundcolor=me.XMLParser.getStringAttribute(e,me.TMX_BACKGROUND_COLOR);this.z=a++;if(this.realwidth<me.game.viewport.width||this.realheight<me.game.viewport.height){var g=~~((me.game.viewport.width-this.realwidth)/2),f=~~((me.game.viewport.height-this.realheight)/2);this.pos.add({x:0<
g?g:0,y:0<f?f:0})}me.TMXUtils.setTMXProperties(this,e);(this.background_color=this.backgroundcolor?this.backgroundcolor:this.background_color)&&this.mapLayers.push(new me.ColorLayer("background_color",this.background_color,a++));this.background_image&&this.mapLayers.push(new me.ImageLayer("background_image",this.width,this.height,this.background_image,a++));break;case me.TMX_TAG_TILESET:this.tilesets||(this.tilesets=new me.TMXTilesetGroup);this.tilesets.add(new me.TMXTileset(c.item(d)));break;case me.TMX_TAG_IMAGE_LAYER:var f=
me.XMLParser.getStringAttribute(c.item(d),me.TMX_TAG_NAME),e=me.XMLParser.getIntAttribute(c.item(d),me.TMX_TAG_WIDTH),g=me.XMLParser.getIntAttribute(c.item(d),me.TMX_TAG_HEIGHT),j=c.item(d).getElementsByTagName(me.TMX_TAG_IMAGE)[0].getAttribute(me.TMX_TAG_SOURCE),e=new me.ImageLayer(f,e*this.tilewidth,g*this.tileheight,j,a++);e.visible=1==me.XMLParser.getIntAttribute(c.item(d),me.TMX_TAG_VISIBLE,1);e.opacity=me.XMLParser.getFloatAttribute(c.item(d),me.TMX_TAG_OPACITY,1);me.TMXUtils.setTMXProperties(e,
c.item(d));this.mapLayers.push(e);break;case me.TMX_TAG_LAYER:j=me.XMLParser.getStringAttribute(c.item(d),me.TMX_TAG_NAME);j.toLowerCase().contains(me.LevelConstants.PARALLAX_MAP)?(e=me.XMLParser.getIntAttribute(c.item(d),me.TMX_TAG_WIDTH),g=me.XMLParser.getIntAttribute(c.item(d),me.TMX_TAG_HEIGHT),f={},me.TMXUtils.setTMXProperties(f,c.item(d)),f.ratio&&(b=f.ratio),e=new me.ImageLayer(j,e*this.tilewidth,g*this.tileheight,f.imagesrc,a++,b),e.visible=1==me.XMLParser.getIntAttribute(c.item(d),me.TMX_TAG_VISIBLE,
1),e.opacity=me.XMLParser.getFloatAttribute(c.item(d),me.TMX_TAG_OPACITY,1),me.TMXUtils.mergeProperties(e,f,!1),b+=b*b,this.mapLayers.push(e)):this.mapLayers.push(new me.TMXLayer(c.item(d),this.tilewidth,this.tileheight,this.orientation,this.tilesets,a++));break;case me.TMX_TAG_OBJECTGROUP:e=me.XMLParser.getStringAttribute(c.item(d),me.TMX_TAG_NAME),this.objectGroups.push(new me.TMXOBjectGroup(e,c.item(d),this.tilesets,a++))}me.XMLParser.free();this.initialized=!0}}})})(window);
(function(){var a=me,b={},c={},d=[],e=0;b.reset=function(){};b.addLevel=function(){throw"melonJS: no level loader defined";};b.addTMXLevel=function(a,b){if(null==c[a])c[a]=new me.TMXTileMap(a,0,0),c[a].name=a,d[d.length]=a;else return!1;b&&b();return!0};b.loadLevel=function(a){a=a.toString().toLowerCase();if(void 0===c[a])throw"melonJS: level "+a+" not found";if(c[a]instanceof me.TMXTileMap){var f=me.state.isRunning();f&&me.state.pause();me.game.reset();me.utils.resetGUID(a);c[b.getCurrentLevelId()]&&
c[b.getCurrentLevelId()].reset();c[a].load();e=d.indexOf(a);me.game.loadTMXLevel(c[a]);f&&me.state.resume()}else throw"melonJS: no level loader defined";return!0};b.getCurrentLevelId=function(){return d[e]};b.reloadLevel=function(){return b.loadLevel(b.getCurrentLevelId())};b.nextLevel=function(){return e+1<d.length?b.loadLevel(d[e+1]):!1};b.previousLevel=function(){return 0<=e-1?b.loadLevel(d[e-1]):!1};a.levelDirector=b})(window);
(function(){me.Tween=function(a){var b={},c={},d={},e=1E3,g=0,f=null,j=0,l=me.Tween.Easing.Linear.EaseNone,m=null,h=null,n=null;this.to=function(c,b){void 0!==b&&(e=b);for(var f in c)null!==a[f]&&(d[f]=c[f]);return this};this.start=function(){me.game.add(this,999);f=me.timer.getTime()+g;j=0;for(var e in d)null!==a[e]&&(b[e]=a[e],c[e]=d[e]-a[e]);return this};this.stop=function(){me.game.remove(this);return this};this.delay=function(a){g=a;return this};me.event.subscribe(me.event.STATE_PAUSE,function(){f&&
(j=me.timer.getTime())});me.event.subscribe(me.event.STATE_RESUME,function(){f&&j&&(f+=me.timer.getTime()-j)});this.easing=function(a){l=a;return this};this.chain=function(a){m=a;return this};this.onUpdate=function(a){h=a;return this};this.onComplete=function(a){n=a;return this};this.update=function(){var d,g,j;g=me.timer.getTime();if(g<f)return!0;if(1<=(g=(g-f)/e))g=1;j=l(g);for(d in c)a[d]=b[d]+c[d]*j;null!==h&&h.call(a,j);return 1===g?(me.game.remove(this),null!==n&&n.call(a),null!==m&&m.start(),
!1):!0};this.destroy=function(){return!0}};me.Tween.Easing={Linear:{},Quadratic:{},Cubic:{},Quartic:{},Quintic:{},Sinusoidal:{},Exponential:{},Circular:{},Elastic:{},Back:{},Bounce:{}};me.Tween.Easing.Linear.EaseNone=function(a){return a};me.Tween.Easing.Quadratic.EaseIn=function(a){return a*a};me.Tween.Easing.Quadratic.EaseOut=function(a){return a*(2-a)};me.Tween.Easing.Quadratic.EaseInOut=function(a){return 1>(a*=2)?0.5*a*a:-0.5*(--a*(a-2)-1)};me.Tween.Easing.Cubic.EaseIn=function(a){return a*a*
a};me.Tween.Easing.Cubic.EaseOut=function(a){return--a*a*a+1};me.Tween.Easing.Cubic.EaseInOut=function(a){return 1>(a*=2)?0.5*a*a*a:0.5*((a-=2)*a*a+2)};me.Tween.Easing.Quartic.EaseIn=function(a){return a*a*a*a};me.Tween.Easing.Quartic.EaseOut=function(a){return 1- --a*a*a*a};me.Tween.Easing.Quartic.EaseInOut=function(a){return 1>(a*=2)?0.5*a*a*a*a:-0.5*((a-=2)*a*a*a-2)};me.Tween.Easing.Quintic.EaseIn=function(a){return a*a*a*a*a};me.Tween.Easing.Quintic.EaseOut=function(a){return--a*a*a*a*a+1};me.Tween.Easing.Quintic.EaseInOut=
function(a){return 1>(a*=2)?0.5*a*a*a*a*a:0.5*((a-=2)*a*a*a*a+2)};me.Tween.Easing.Sinusoidal.EaseIn=function(a){return 1-Math.cos(a*Math.PI/2)};me.Tween.Easing.Sinusoidal.EaseOut=function(a){return Math.sin(a*Math.PI/2)};me.Tween.Easing.Sinusoidal.EaseInOut=function(a){return 0.5*(1-Math.cos(Math.PI*a))};me.Tween.Easing.Exponential.EaseIn=function(a){return 0===a?0:Math.pow(1024,a-1)};me.Tween.Easing.Exponential.EaseOut=function(a){return 1===a?1:1-Math.pow(2,-10*a)};me.Tween.Easing.Exponential.EaseInOut=
function(a){return 0===a?0:1===a?1:1>(a*=2)?0.5*Math.pow(1024,a-1):0.5*(-Math.pow(2,-10*(a-1))+2)};me.Tween.Easing.Circular.EaseIn=function(a){return 1-Math.sqrt(1-a*a)};me.Tween.Easing.Circular.EaseOut=function(a){return Math.sqrt(1- --a*a)};me.Tween.Easing.Circular.EaseInOut=function(a){return 1>(a*=2)?-0.5*(Math.sqrt(1-a*a)-1):0.5*(Math.sqrt(1-(a-=2)*a)+1)};me.Tween.Easing.Elastic.EaseIn=function(a){var b,c=0.1;if(0===a)return 0;if(1===a)return 1;!c||1>c?(c=1,b=0.1):b=0.4*Math.asin(1/c)/(2*Math.PI);
return-(c*Math.pow(2,10*(a-=1))*Math.sin((a-b)*2*Math.PI/0.4))};me.Tween.Easing.Elastic.EaseOut=function(a){var b,c=0.1;if(0===a)return 0;if(1===a)return 1;!c||1>c?(c=1,b=0.1):b=0.4*Math.asin(1/c)/(2*Math.PI);return c*Math.pow(2,-10*a)*Math.sin((a-b)*2*Math.PI/0.4)+1};me.Tween.Easing.Elastic.EaseInOut=function(a){var b,c=0.1;if(0===a)return 0;if(1===a)return 1;!c||1>c?(c=1,b=0.1):b=0.4*Math.asin(1/c)/(2*Math.PI);return 1>(a*=2)?-0.5*c*Math.pow(2,10*(a-=1))*Math.sin((a-b)*2*Math.PI/0.4):0.5*c*Math.pow(2,
-10*(a-=1))*Math.sin((a-b)*2*Math.PI/0.4)+1};me.Tween.Easing.Back.EaseIn=function(a){return a*a*(2.70158*a-1.70158)};me.Tween.Easing.Back.EaseOut=function(a){return--a*a*(2.70158*a+1.70158)+1};me.Tween.Easing.Back.EaseInOut=function(a){return 1>(a*=2)?0.5*a*a*(3.5949095*a-2.5949095):0.5*((a-=2)*a*(3.5949095*a+2.5949095)+2)};me.Tween.Easing.Bounce.EaseIn=function(a){return 1-me.Tween.Easing.Bounce.EaseOut(1-a)};me.Tween.Easing.Bounce.EaseOut=function(a){return a<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=
1.5/2.75)*a+0.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+0.9375:7.5625*(a-=2.625/2.75)*a+0.984375};me.Tween.Easing.Bounce.EaseInOut=function(a){return 0.5>a?0.5*me.Tween.Easing.Bounce.EaseIn(2*a):0.5*me.Tween.Easing.Bounce.EaseOut(2*a-1)+0.5}})();
(function(){var a=me,b={},c={};b.STATE_PAUSE="me.state.onPause";b.STATE_RESUME="me.state.onResume";b.GAME_INIT="me.game.onInit";b.LEVEL_LOADED="me.game.onLevelLoaded";b.LOADER_COMPLETE="me.loader.onload";b.LOADER_PROGRESS="me.loader.onProgress";b.KEYDOWN="me.input.keydown";b.KEYUP="me.input.keyup";b.WINDOW_ONRESIZE="window.onresize";b.publish=function(a,b){for(var g=c[a],f=g?g.length:0;f--;)g[f].apply(window,b||[])};b.subscribe=function(a,b){c[a]||(c[a]=[]);c[a].push(b);return[a,b]};b.unsubscribe=
function(a,b){for(var g=c[b?a:a[0]],b=b||a[1],f=g?g.length:0;f--;)g[f]===b&&g.splice(f,1)};a.event=b})();
(function(){var a=me,b={};b.Base=Object.extend({version:void 0,init:function(){}});b.patch=function(a,b,e){void 0!==a.prototype&&(a=a.prototype);if("function"==typeof a[b]){var g=a[b];a[b]=function(){var a=this.parent;this.parent=g;var b=e.apply(this,arguments);this.parent=a;return b}}else console.error(b+" is not an existing function")};b.register=function(a,b){me.plugin[b]&&console.error("plugin "+b+" already registered");if(void 0===a.prototype.version)throw"melonJS: Plugin version not defined !";
if(0<me.sys.checkVersion(a.prototype.version))throw"melonJS: Plugin version mismatch, expected: "+a.prototype.version+", got: "+me.version;me.plugin[b]=new a;if(!(me.plugin[b]instanceof me.plugin.Base))throw"melonJS: Plugin should extend the me.plugin.Base Class !";};a.plugin=b})();
